### ISSUE TITLE
Facebook metadata for better sharing

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#159]
~~Dublin Core elements in header?~~
Facebook Open Graph tags are required.

**Comment by Siggik** [comment]
Kunne være superfedt. Lige nu kommer events billeder f.eks. ikke med når man deler på facebook. Det kunne være sejt hvis de gjorde. Vi kommer til af den vej rundt at prøve at hive folk fra facebook over på dukop.

**Comment by Siggik** [comment]
En ven forslår på facebook at der i linket på facebook også kommer til fremstår tidspunkt og sted i linket. Se her: https://www.facebook.com/groups/207178482660270/1058406790870764/?comment_id=1060217314023045&notif_t=like

**Comment by ronan-mch** [comment]
This is nearly complete - the only thing missing is to move the `<meta>` tags into the document head.

**Comment by Siggik** [comment]
jeg hepper:)

**Comment by ronan-mch** [comment]
Hej, du kan få en sneak preview af hvordan Facebook forstår de nye tags ved at kigge på deres [URL Debugger](https://developers.facebook.com/tools/debug/og/object/?q=http%3A%2F%2Fthawing-dawn-8343.herokuapp.com%2Fevents%2F189%3Flocale%3Dda). Jeg er ikke helt sikker på hvordan datoen bedst skal formateres men jeg tænker at f.eks. `30 mar` er ok.

**Comment by Siggik** [comment]
Kan man få det til at ligne den måde facebook selv sætter det op, se f.eks. events her: https://www.facebook.com/folketshus50/ , Tror det vil være mest naaturligt for folk

**Comment by ronan-mch** [comment]
Hvad mener du? Vi snakker om share dialogen, ikke?

Den tor. 31. mar. 2016 09.16 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Ja, jeg mener: Facebooks egne events ser ud på en bestemt måde når man deler(share) dem. Måske det vil give mening at prøve at så vidt muligt at efterligne det. Så ligner det mest muligt noget folk er vant til.

**Comment by ronan-mch** [comment]
Det er ikke muligt at dele eksterne events som sådan til Facebook:
https://developers.facebook.com/docs/reference/opengraph#object-type

Derfor bliver det altid en hack at få event metadata at passe ind i deres
Open Graph syntaks.

Den tor. 31. mar. 2016 10.15 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Ok, I see.
