### ISSUE TITLE
Bedre forklaring på opret bruger side

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#160]
Dvs. forskellen mellem de forskellige brugertyper og tilhørende rettigheder. Vedhæftet billede er en mulighed.
![create user](https://cloud.githubusercontent.com/assets/1145457/5988562/17dcc26c-a966-11e4-8a04-a83a1e6d305a.jpg)

**Comment by tokefrello** [comment]
Jeg har kigget lidt på, hvordan vi kan formatere login-siden mere klart, så det ikke bare er links. Jeg er dog lidt usikker på, hvordan jeg skal opdele koden. "Opret anonym bruger" er i en .erb-fil, de andre links er i en anden.

Er det muligt at flytte "Opret anonym bruger" til den samme fil som de andre, eller synes du i stedet, jeg skal formatere på tværs af de to filer? Det sidste ville nok medføre en del komplikationer.

**Comment by ronan-mch** [comment]
Jeg vil gerne prøve at gøre det lidt nemmere at arbejde med.

søn. 1. feb. 2015 11.24 skrev tokefrello <notifications@github.com>:

**Comment by ronan-mch** [comment]
jeg har lagt en ny [Opret Konto side](http://thawing-dawn-8343.herokuapp.com/new_account?locale=da) der linker til de to muligheder sammen med en kort forklaring. Styling er helt hat og briller, men det går jeg ud fra at du kan gøre noget ved :wink: 

Jeg har også fjernet det der anonym link ting, da jeg synes at det er unødvendigt der nu.
