### ISSUE TITLE
lokation

### ISSUE THREAD

**Issue by tonesnye** [ronan-mch/det_sker#170]
lokation knappen fungere ikke for den anonyme bruger. jeg prøver at oprette sankt hans torv som lokation, men den går ligesom bare i frys, når jeg trykker opret.

**Comment by ronan-mch** [comment]
can't reproduce...

**Comment by ronan-mch** [comment]
problemet er også nævnt i #176 - beklager, det tog mig lidt tid at opdage hvad fejlen var. Den burde være løst nu.
