### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by tonesnye** [ronan-mch/det_sker#171]
Jeg kan ikke klikke at noget er ugentligt, hvis jeg er anonym

**Comment by tonesnye** [comment]
det kan jeg heller ikke hvis jeg har en bruger, faktisk. det kunne være meget nice

**Comment by ronan-mch** [comment]
indtil videre har vi ikke lavet gentaget events. Jeg vil gerne lave det, har bare ikke fået det gjort endnu.
