### ISSUE TITLE
something wrong with locations#index page

### ISSUE THREAD

**Issue by tonesnye** [ronan-mch/det_sker#172]
Når jeg trykker på "lokationer", kkan jeg se at der er sket en fejl, da jeg har oprettet en begivenhed. den har oprettet to lokationer for Sankt Hans Torv, den ene med et link på, der ikke fører nogen steder...

**Comment by ronan-mch** [comment]
jeg tror ikke at den opretter den forkerte. Jeg tror bare at visning af lokationer ikke er særlig god. Jeg skal nok gøre noget ved det.
