### ISSUE TITLE
kan ikke oprette lokation

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#176]
Evt. pga. af for lang beskrivelse? 

![screenshot from 2015-03-12 20 50 33](https://cloud.githubusercontent.com/assets/7570153/6626789/b5853406-c8f9-11e4-84e6-8538186f45e7.png)

**Comment by ronan-mch** [comment]
Det bør ikke rigtig have noget med beskrivelsen at gøre. Jeg prøvede lige
at sakse en lang beskrivelse ind for en sikkerheds skyld og det havde ikke
nogen indflydelse. Jeg begynder at mistænke at det har noget med din egen
sæt op at gøre. Har du nogle særlige sikkerheds indstillinger i Iceweasel
der har med AJAX eller javascript at gøre? Gider du prøve den samme på en
Firefox eller Chromium for at sikre dig at det ikke er noget med IceWeasel?

2015-03-12 20:52 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Nej det er nok ikke beskrivelsen, prøvede det lige uden beskrivelse og det var det samme. 

Jeg har ikke andet end iceweasel. Du kan ikke få den til at lave samme fejl? Er der en med en browser der kan test det? @tadoh @dotnetCarpenter ? En løsning for nu kunne være hvis du oprettede de 5-6 mest brugte steder. så tester jeg det ved lejlighed på en anden computer.

**Comment by Siggik** [comment]
Jeg får samme fejl med chronium:

![lokation oprettelse fejl](https://cloud.githubusercontent.com/assets/7570153/6635948/910acb78-c96b-11e4-90c6-00191b47fe43.png)

**Comment by ronan-mch** [comment]
Ok, jeg har lige prøvet med Chrome og det virker fint for mig. Kan jeg få
dig til at gøre det samme med Chrome (det virker nok også med Iceweasel)
men INDEN du klikker på knappen tryk på F12 og så på Network i Vinduet der
popper op i bunden. Her kan du overvåge network forespørgsel lavet af siden
og hvordan de svarer.
Klik så på Opret lokation knappen. Der burde komme en ny post i Network
tabellen. Klik på den og inspicere den. Tage endelig billeder af
resultatet, især Headers og Response.

2015-03-13 10:27 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Ok, her får du en lange række screenshots. Lavet i Iceweasel. Først fra at have trykket på "Opret lokation"

![screenshot from 2015-03-14 09 18 42](https://cloud.githubusercontent.com/assets/7570153/6650912/4087f890-ca2b-11e4-8caa-47734d17ad87.png)
![screenshot from 2015-03-14 09 18 37](https://cloud.githubusercontent.com/assets/7570153/6650914/408a5324-ca2b-11e4-9f12-fc000e47bdcd.png)
![screenshot from 2015-03-14 09 18 32](https://cloud.githubusercontent.com/assets/7570153/6650913/408a15b2-ca2b-11e4-9d91-ad41c4acce08.png)

Og her efter at have udfyldt formularen og trykket opret:

![screenshot from 2015-03-14 09 20 52](https://cloud.githubusercontent.com/assets/7570153/6650919/99aad5b4-ca2b-11e4-86d2-3c07fd4f88ed.png)
![screenshot from 2015-03-14 09 20 47](https://cloud.githubusercontent.com/assets/7570153/6650920/99c0188e-ca2b-11e4-942a-fadab7135877.png)
![screenshot from 2015-03-14 09 20 42](https://cloud.githubusercontent.com/assets/7570153/6650921/99c058f8-ca2b-11e4-8813-f81c48ab5eb3.png)

**Comment by ronan-mch** [comment]
Tak for screenshots. De siger at AJAX forespørgslen virkede rigtig men på en eller anden grund blev resultatet ikke lagt i modal vinduet. Gider du prøve det samme igen men denne gang kigge på Console i developer tools (det med F12) for at se om der kom en fejl besked?

**Comment by ronan-mch** [comment]
Det er løst i e77b56c156201f89d310d8f1e56d110848f6ae8e. Jeg beder dig om at teste når jeg har lagt en ny udgave på dukop.dk.

**Comment by ronan-mch** [comment]
Og tak i øvrigt for meget grundig fejl dokumentation. Sådan ting er ofte svær at forklare når man ikke kigger på skærmen samtidig.

**Comment by ronan-mch** [comment]
Jeg har lagt en ny udgave op. Du må gerne teste den og bekræfte at fejlen er løst.

**Comment by Siggik** [comment]
Sejt. Jeg tester.... Nu kommer der en flot grøn kasse op og siger at lokationen er oprettet.... Men den fremgår ikke af listen efterfølgende. Heller ikke efter jeg reefreshes siden.

**Comment by ronan-mch** [comment]
Ok, jeg lukker sagen så. Det med typeahead er noteret i #181. Jeg løser snart.
