### ISSUE TITLE
fejlmelding ved oprettelse af event når der ikke er valgt lokation

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#177]
Efter dennde udfyldelse

![screenshot from 2015-03-12 21 14 07](https://cloud.githubusercontent.com/assets/7570153/6627223/ded16a02-c8fc-11e4-899a-a2ba96f319f2.png)

kommer denne fejl:

![screenshot from 2015-03-12 21 12 19](https://cloud.githubusercontent.com/assets/7570153/6627210/baaebd0a-c8fc-11e4-99da-e0f593556a46.png)

**Comment by ronan-mch** [comment]
jeg kan ikke se noget i denne screenshot udover en grå skærm - er det det
du fik? Var der ellers noget usædvanlig med oprettelsen? Jeg kan se at det
er lykkedes dig at oprette en event Folkets Haus - gjorde du noget
anderledes denne gang?

**Comment by Siggik** [comment]
Nicola lavede den med hoveadmin brugeren. Ja, undskyld. Der kom Tor hvis lige i vejen:) Der stor bare samme kode som står i headeren: 502 bad gateway.

**Comment by ronan-mch** [comment]
jeg mistænker at det har noget at gøre med at du ikke har valgt en lokation. Men når jeg prøver at genskabe det, så får jeg ikke lov til at komme videre i stedet for en fejl side. Hvor stor var billedet i øvrigt? Hvis den er over 1M så får man en fejl side, men det er en 413 i stedet for en 502.

**Comment by Siggik** [comment]
Du har helt ret. Jeg lavede testen med eller uden lokation. Hvis der ikke er lokation kommer fejlen. Ændrer titlen af buggen til at der skal komme en reminder om at sætte lokation.

**Comment by ronan-mch** [comment]
Jeg har lavet sådan en advarsel i 54a41964c7ea91b012fd2ac8baff60ea1abbd320, men det er alligevel ikke ok at man kommer til sådan en fejl side. Når jeg gøre det bliver jeg på siden og der bliver spyttet en advarsel ud. Jeg forstår ikke hvorfor det samme ikke gælder for dig.
