### ISSUE TITLE
beskrivelsesfeltet har begræsning for lang tektsen må være....

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#188]
.....som er er alt for kort. 

denne tekst kunne ikke være der:

"Foredraget kommer til at handle om hvad de spanske anarkister i slutningen af 1800-tallet og begyndelsen af 1900-tallet mente om litteratur og hvordan deres politiske agendaer og æstetik flød sammen til en slags kunstaktivisme i grænselandet mellem skønlitteratur og propaganda. Emner som jeg vil tage op bliver anarkisternes syn på naturen, bondestandens vilkår, religion, kapitalens undertrykkelse af arbejdere og fattige, feminismen og den sociale revolution. Indimellem jeg læse tekster op - i samarbejde med skuespilleren Peter Vadsager - fra den nyudgivne antologi Hjernedynamit, fra Forlaget Det Poetiske Bureau, som vil understrege anarkisternes pointer i praktisk kunstnerisk forstand. Vel mødt til en aften i selskab med de spanske anarkister og deres litteratur. "

Se også scrennshot: 
![screenshot from 2015-03-29 15 44 23](https://cloud.githubusercontent.com/assets/7570153/6885678/f601cd08-d62a-11e4-8dc0-8f9bc8306843.png)

**Comment by benjaoming** [comment]
True dat. Rækkefølgen kan gøres bedre. Det kan jeg godt kigge på ifm
UI-opdateringen.

Ideelt set lave man tidspunkt og sted først... og beskrivelse og billede
til sidst... den slags kræver nok flere overvejelser og "nørkleri", derfor
bedre at lægge ind efter de mere simple facts...

Titel-feltet skal også reflektere den tilsigtede længde på titler.

2015-03-29 15:48 GMT+02:00 Siggik <notifications@github.com>:

**Comment by ronan-mch** [comment]
Fixed in 0697d31d61e80d59493b9c64d0bbda22b3ee5a27
