### ISSUE TITLE
Fejl på lokation side når logget ind som anonym bruger

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#189]
ser fint ud når man sætter musen henover lokationen: 

![screenshot from 2015-03-29 15 50 56](https://cloud.githubusercontent.com/assets/7570153/6885935/a917a6ce-d62b-11e4-8160-2ea09e7ca590.png)

Men ikke når man trykker: 
![screenshot from 2015-03-29 15 50 59](https://cloud.githubusercontent.com/assets/7570153/6885937/b2dd8cdc-d62b-11e4-8011-6ec4cba598e3.png)

**Comment by ronan-mch** [comment]
![locations](https://cloud.githubusercontent.com/assets/1145457/6887572/0ce85eb8-d664-11e4-908b-a331d0a6cae8.png)

Underligt, det virker fint for mig...

**Comment by tadoh** [comment]
Virker hellere ikke for mig. Bruger Ubuntu 15.04 og Firefox 37.0

Har prøvet kl. 12.52 d. 9. juni

**Comment by ronan-mch** [comment]
kan du sende mig den url du klikkede på? Jeg har prøvet dem alle sammen og
de virker for mig.

2015-06-09 12:52 GMT+02:00 tadoh <notifications@github.com>:

**Comment by ronan-mch** [comment]
nu har jeg sgu fundet det! Jeg kunne ikke genproducere det fordi det havde noget at gøre med om man er anonym bruger. Jeg laver en fix snarest. Tak for fejlmeddelsen og tak for timestamp, ellers havde jeg ikke fundet fejl beskeden.

**Comment by Siggik** [comment]
Sejt!

**Comment by ronan-mch** [comment]
fix deployed to production.
