### ISSUE TITLE
fejl ved log in mandag den 25. kl 11.31

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#194]
Efter at have tastet mail eller kode forkert prøvede jeg at taste på log in på ekstisterede konto igen, så kom denne meddelelse. Efter så at gå tilbage og prøve igen, virkede det.

![screenshot from 2015-05-25 11 31 32](https://cloud.githubusercontent.com/assets/7570153/7795112/ee801b88-02d1-11e5-9ca4-858270c19a3f.png)

**Comment by ronan-mch** [comment]
Tak,jeg tjekker det.

man. 25. maj 2015 11.35 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
og nu prøvede jeg at oprette en bruger og fik samme fejl, 12.02: 

![screenshot from 2015-05-25 12 02 27](https://cloud.githubusercontent.com/assets/7570153/7795537/464ffa8c-02d6-11e5-8fa3-a3cc2a9f89b8.png)

Den var udfyldt således: 
![screenshot from 2015-05-25 12 03 22](https://cloud.githubusercontent.com/assets/7570153/7795545/58b3b8a8-02d6-11e5-810d-fad7d3602585.png)

**Comment by Siggik** [comment]
næste kapitel: 

Jeg prøvede at lave en bruger uden mellemrum. Så virkede det.Hvis brugere ikke kan have mellemrum, skal der så ikke laves en specifik fejlmeddelses til det? 

jeg fik så denne side op: 
![screenshot from 2015-05-25 12 05 42](https://cloud.githubusercontent.com/assets/7570153/7795589/b2451d9e-02d6-11e5-9a0a-5f82ef48f0cd.png)

Den siger først alt er fint i den grønneboks og så derefter at mailen allerede blir brugt. Er den brugt? Jeg tror kun at det er mig og Nicola  der har koden...?

**Comment by ronan-mch** [comment]
har du fået en bekræftelses mail?

2015-05-25 12:10 GMT+02:00 Siggik <notifications@github.com>:

**Comment by ronan-mch** [comment]
bruger Dukop Admin er oprettet og jeg har gjort dig til admin. Fik I
nogensinde den bekræftelses mail? Ifølge log filen burde den have blevet
sendt.

2015-05-25 15:05 GMT+02:00 Ronan McHugh <mchugh.r@gmail.com>:

**Comment by Siggik** [comment]
cool. Jeg fik mailen og den er nu oprettet.

**Comment by ronan-mch** [comment]
kan du fortælle mig hvor længe der gik mellem du oprettede dig og du fik
mailen?

**Comment by Siggik** [comment]
Jeg tog screenshottet 2 minutter efter jeg fik mailen. Hvilket jo må betyde at jeg har fået mailen med det samme og så stenede i 2 minutter før jeg fik lavet screenshottet.

**Comment by ronan-mch** [comment]
ok, godt at vide.

2015-05-27 10:57 GMT+01:00 Siggik <notifications@github.com>:
