### ISSUE TITLE
begivenheds problemer

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#195]
Nu prøver jeg at oprette betatest event. Jeg oprettede en lokation som hed intet sted. Men den optræder ikke af listen. (14.34)

![screenshot from 2015-05-26 14 34 55](https://cloud.githubusercontent.com/assets/7570153/7812685/106bf01c-03b5-11e5-8c48-747ba1fe24f1.png)

Bolsje og Bumzen optræder 2 gange. Kan du rette det?

**Comment by ronan-mch** [comment]
Det kan du - du er admin. Gå ind under lokationer og slette dem som ikke
bør være der. Gør endelig det samme med Brugere og Kategorier. Denne boks
er en typeahead, dvs. at du skal taste for at finde den rigtige frem.
