### ISSUE TITLE
fejl 

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#198]
Når jeg trykker på lokationer her: 
![screenshot from 2015-05-27 13 30 58](https://cloud.githubusercontent.com/assets/7570153/7834933/ebd906e8-0474-11e5-80b4-29bd377195c1.png)

Får jeg denne her fejl: 
![screenshot from 2015-05-27 13 29 01](https://cloud.githubusercontent.com/assets/7570153/7834937/f9208024-0474-11e5-9004-fa01f82da769.png)

**Comment by ronan-mch** [comment]
der er ikke noget problem med denne side naar jeg tjekker det. jeg
mistaenker at det er noget med serveren der driller.
