### ISSUE TITLE
implement unicorn worker killer

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#201]
https://www.digitalocean.com/community/tutorials/how-to-optimize-unicorn-workers-in-a-ruby-on-rails-app

https://github.com/kzk/unicorn-worker-killer

**Comment by dotnetCarpenter** [comment]
Why does Ruby get all the awesome project names?!?

**Comment by benjaoming** [comment]
[it doesn't](https://github.com/jmoiron/johnny-cache) :)

**Comment by ronan-mch** [comment]
Implemented. No down time since then, but not sure the issue is solved once and for all.
