### ISSUE TITLE
Hide edit buttons when user not able to use them

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#205]
I bunden af eventet, når den bliver vist stort, med alle detaljer, står der en Edit knap. Jeg får at vide at 
"Du er ikke tilladt at bruge denne side" (skal måske også rettes til "Du har ikke rettigheder til at redigere denne begivenhed" eller noget).

Men hvad er knappens funktion? Er det for at give admin og ejeren mulighed for at rette?

**Comment by ronan-mch** [comment]
ja det er kun for admin. det burde egentlig skjules når vedkommende ikke
har adgang til det.

2015-06-09 13:08 GMT+02:00 tadoh <notifications@github.com>:
