### ISSUE TITLE
Ingen formatering på event tekst

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#206]
Så er vi sku i gang. Spændende at se om folk begynder at bruge det i morgen!

Når man laver linieskift i event tekst, så forsvinder det, når det blir oprettet. Det gør det ret uoverskuelig at læse længere eventtekst. Kan det laves om reletivt let?

**Comment by ronan-mch** [comment]
Ja, jeg tror at det er meget muligt. Jeg kigger på det snarest.

http://api.rubyonrails.org/classes/ActionView/Helpers/TextHelper.html#method-i-simple_format

**Comment by ronan-mch** [comment]
Fix deployed to staging, you can see it [here](http://thawing-dawn-8343.herokuapp.com/events/1?locale=da). I'll do a combined update at the weekend. Probably Sunday...
