### ISSUE TITLE
Give users ability to enable comments on their event

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#210]
Måske kunne det være fedt at give mulighed for at fravælge det, i stedet for at skulle vælge det til?

**Comment by ronan-mch** [comment]
lige nu er det kun admin bruger der har mulighed for at tillade kommentarer
eller ej. Det har jeg valgt fordi jeg ikke er trygge nok med
funktionaliteten eller dens mulige afkom. Jeg er nemlig bange for at med
kommentarer kunne Duk op blive til et konstant flame war og det gider jeg
virkelig ikke. Jeg synes vi skal prøve at tage emnet op til opsamlingsmødet.

2015-06-11 11:59 GMT+02:00 tadoh <notifications@github.com>:

**Comment by ronan-mch** [comment]
nu har vi aftalte at vi giver brugerne lov til at vælge selv om de skal have kommentarer på deres event.
