### ISSUE TITLE
præsentation af slette event

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#214]
Skal der ikke være en mulighed for at slette et event helt? Aflysning er cool, men man skal også kunne fjerne det det helt? right?

![screenshot from 2015-08-24 11 15 50](https://cloud.githubusercontent.com/assets/7570153/9436724/b16e14f8-4a51-11e5-9128-6a6ba26d04a7.png)

**Comment by ronan-mch** [comment]
Det kan man godt fra forsiden. Vi kan godt lægge en knap et andet sted hvis det er.

**Comment by Siggik** [comment]
ja, måske også her ved siden af aflyst begivenhedsknappen?
