### ISSUE TITLE
generel snak om gentagelse af events

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#215]
.... fyr løs...

**Comment by Siggik** [comment]
Billede: "choose file" knappen virker ikke

**Comment by Siggik** [comment]
Jeg glemte at udfylde hvilken uge dag der skulle gentages. Da jeg trykkede opret skete der ikke noget, jeg fik heller ikke en besked om hvad jeg havde glemt at udfylde. Det tog mig 5 minutter at fatte det - det går ikke hurtigt i dag:)

**Comment by Siggik** [comment]
Kan redigerer alle events muligheden og ligge under redigere knappen? :

![screenshot from 2015-08-24 11 55 21](https://cloud.githubusercontent.com/assets/7570153/9437550/68cecdea-4a57-11e5-8ee1-f3eb9aee2908.png)

**Comment by ronan-mch** [comment]
> Kan redigerer alle events muligheden og ligge under redigere knappen? 

Jeg og Amalie blev enige om at denne knap skulle fjernes fra forsiden for at indfri mere plads. Hvis du ikke mener at det er en god idé må du gerne tage den med hende ;)

> Billede: "choose file" knappen virker ikke 
> Jeg glemte at udfylde hvilken uge dag der skulle gentages. Da jeg trykkede opret skete der ikke noget, jeg fik heller ikke en besked om hvad jeg havde glemt at udfylde. Det tog mig 5 minutter at fatte det - det går ikke hurtigt i dag:)

Ok, jeg kigger på det.

**Comment by Siggik** [comment]
Jeg er ikke sikker på med det med redigere knappen på forsiden. Lad os bare prøve det som dig og Amalie blev enige om, Men foroven har jeg medvilje valgt ikke at vise knappen på forsiden men under "mine begivenheder"

**Comment by Siggik** [comment]
Det virker umiddelbart til at virke perfekt!

**Comment by Siggik** [comment]
jeg skriver ud til folk at de skal teste det.
