### ISSUE TITLE
Under konstruktion banner eller ligenende...

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#216]
Kan der komm et rødt banner i Toppen som siger noget a la at siden stadig er under konstruktion og den først blir rigtig lanceret engang i efteråret. Folk er dog meget velkomne til at bruge den nu og komme med feedback til dukop@riseup.net hvis de har lyst?

**Comment by ronan-mch** [comment]
Ja, det kan jeg godt finde ud af.

man. 24. aug. 2015 12.41 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
sejt!

**Comment by ronan-mch** [comment]
Denne feature er nu implementeret som Nyheder og er desuden deployet til produktion. Jeg foreslår at du selv opretter en post for at se hvordan den fungerer. Det gøre du fra [denne side](https://dukop.dk/news?locale=da) når du er logget ind som administrator.

**Comment by ronan-mch** [comment]
Eftersom jeg ikke fik svar til ovenstående har jeg lavet banner-en selv.

**Comment by Siggik** [comment]
Det ser smukt ud!
