### ISSUE TITLE
Recurring events count as individual events in the tag system

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#217]
Yoga and Kung-fu appear as 35 individual events in the "typer" and "steder" menus on the right.

Should probably just count as one event?

**Comment by ronan-mch** [comment]
Why do you think so? I would see them as different events. That said, I
think there should be an additional filter option to filter out the regular
events and just see the exciting stuff.

**Comment by tadoh** [comment]
Hmm... I don't know. I just think that seeing that big number on the side is misleading. But perhaps it should stay as it is and with time add a filter as you say

**Comment by ronan-mch** [comment]
what do the others say? I guess you've had a meeting based on the sudden
flurry of mails ;)

**Comment by Siggik** [comment]
Hmm, jeg tænker umiddelbart at det måske er ok at det fremgår. Jeg har ikke en stærk holdning til det.

**Comment by ronan-mch** [comment]
Ok, jeg lukker denne indtil videre. I skal være velkommen til at genåbne hvis det bliver relevant.
