### ISSUE TITLE
Beskrivelse af bruger

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#218]
jeg tænker det kunne være nice med en feature hvor brugernes kan skrive lidt om dem selv. Det kunne være en tekstboks når man opretter brugeren og en redigér knap på bruger siden,når man er logget ind: https://dukop.dk/users/3?locale=da

**Comment by ronan-mch** [comment]
det er nemt nok at lave.

2015-09-21 20:20 GMT+02:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Fedt:)

**Comment by ronan-mch** [comment]
Det er nu lavet og oppe på staging. Venligst test og meld tilbage i tråden om den duer.

**Comment by Siggik** [comment]
hvad er adressen nu på staging serveren?

**Comment by ronan-mch** [comment]
du kan nu komme til det ved staging.dukop.dk. Det kunne godt være at du møder en sikkerheds fejl, i så fald skal du rydde din browser cache og prøve igen.

**Comment by Siggik** [comment]
Det er en untrusted connection?

**Comment by ronan-mch** [comment]
ja, fordi den er egentlig bare en redirect til heroku. jeg kan ikke umiddelbart se hvordan man sletter den rigtig del af historik i browseren, det kunne være at @benjaoming kan hjælpe. Ellers gå bare direkte hen til http://thawing-dawn-8343.herokuapp.com/

**Comment by benjaoming** [comment]
@Siggik sørg for at skrive http://staging.dukop.dk (eller bare klik på det her link). Evt. slet din browser cache, hvis du alligevel havner på noget SSL.

**Comment by Siggik** [comment]
Efter jeg lavede brugeren. Kunne jeg via redigerinsknap redigere brugeren. Det virkede fint. Jeg fik dog ikke muligheden for at skrive noget om min nye bruger mens jeg lavede den...

**Comment by ronan-mch** [comment]
Hej Sigge, god pointe. Jeg har rettet det og nu burde det virke som en del af oprettelses flow-en. Du må gerne tjekke igen for en god ordens skyld.

**Comment by Siggik** [comment]
Tak:) Det ser ud til at virke! 

Måske skal feltet være lidt større? Og en dansk tekst. Måske bare "Beskrivelse"

**Comment by ronan-mch** [comment]
Ja

fre. 30. okt. 2015 12.14 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Ser rigtig godt ud nu!
