### ISSUE TITLE
Recurring events doesn't work

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#219]
From thawing-dawn version.

Recurring events says I should choose a category, despite the fact I have chosen one.
I keep getting the error and cannot create the event.

Last happened the 21st september at 20:48

**Comment by ronan-mch** [comment]
It looks like there's something wrong with the javascript on the test site
now. Don't know what's going on there...

**Comment by ronan-mch** [comment]
sorry, I'm wrong, the javascript thing is a non-issue, the problem is as
you report. I don't know what it is but I'll sort it asap.

**Comment by tadoh** [comment]
cool ;)

**Comment by ronan-mch** [comment]
Hey, sorry about the delay fixing this. There was a problem with the sample data on the test site. It's been fixed now.
