### ISSUE TITLE
Event billeder blir ikke vist.

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#221]
De to event, der nu ligger på dukop.dk har begge problemer med billedet. På betatest eventen fremgår billedets navn, men ikke selve billedet. På brunch eventet, kan billedet slet ikke ses.

**Comment by Siggik** [comment]
hov, nu prøvede at jeg at sætte brunch billedet ind igen via redigeringsknappen. Det ser ud til at virke nu. Der skal dog nok lidt design ind over det :)

**Comment by ronan-mch** [comment]
Ja, men det burde virke uden at du skulle gøre det igen. Jeg kigger på det. Tak for feedback.

**Comment by ronan-mch** [comment]
Fixed.

**Comment by ronan-mch** [comment]
Fix lagt på prod.

**Comment by Siggik** [comment]
Nice og kan se at du har rykket på billede thumbnailen. Det ser ret ud på forsiden nu.
