### ISSUE TITLE
Manglende icons

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#224]
Der mangler icons i tidsangivelses applicationen:

![manglende pile i tidsangivelse](https://cloud.githubusercontent.com/assets/7570153/10369545/19189c70-6ddb-11e5-814f-75af5d2f732b.jpg)

Samme firkant optræder ved siden af navnet på brugeren når man er logget ind og ved siden af kategori navnet når man har trykket på det.

**Comment by ronan-mch** [comment]
Ok, jeg kigger på det.
