### ISSUE TITLE
manglende indryk af begivenhedstekst på forsiden.

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#225]
Måske sker fejlen når eventet oprettet af anonymebrugere? Det sker i hvert fald ikke med de andre event der er oprettet pt.:

![event tekst pa forsiden](https://cloud.githubusercontent.com/assets/7570153/10370633/17aeb40a-6de0-11e5-8ee9-eaf6d0fa8b1a.png)

**Comment by ronan-mch** [comment]
Det er rettet i fa09b0e609dcefecc116dacf96dcc9535bbd9049
