### ISSUE TITLE
Kommentar funktion ikke til stede på mobil

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#227]
Man kan ikke se kommentarer eller skrive når man ser hjemmesiden på mobil browser. jeg bruger android. 

Men den er derudover overraskende nice på mobil! Men blir lige ved at teste siden på den platform de næste dage...

**Comment by ronan-mch** [comment]
Hej, synes du at alle funktionalitet skal også være tilgængelig på mobilen? Jeg tænkte at nogle oprettelses ting kunne være for fedtet på sådan en lille skærm og så tænkte jeg lige så godt at man kunne skjule dem. Det der med at læse kommentar og dog en fejl. 

Og hvad mener du overraskende nice? Jeg har faktisk brugt tid på det!

**Comment by Siggik** [comment]
"Overraskende nice" var ment som ros. Dvs. at jeg kan se at du har brugt tid og energi på det og at resultatet er godt. . "Overraskende", da Jeg har ikke selv har brugt den så meget og da jeg ikke vidste at du havde brugt så meget tid på det og "overraskende", da jeg fornyelig har set nogle meget frygtelig mobil netsider. Dvs. jeg kunne også bare have skrevet: Jeg synes mobilsiden er super flot! 

I forhold til hvad der skal være tilgængeligt på mobilsiden, så har jeg ikke en fast holdning. Men dine overvejelser lyder fornuftige. Jeg gir en feedback når jeg har brugt mobil udgaven et par gange...

**Comment by ronan-mch** [comment]
Ok, bare rolig det var bare for sjovt.

tor. 22. okt. 2015 11.10 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
ok:)

**Comment by Siggik** [comment]
Nu har jeg fundet en funktion på mobilen som jeg havde brug for men ikke kunne finde. Jeg oprettede et event, men lavede en fejl jeg gerne ville rette. Jeg tror det ville være godt, at man kan redigere events på mobilen også. Gir det ikke mening?

**Comment by ronan-mch** [comment]
Jo da, det kigger jeg på

tor. 22. okt. 2015 16.26 skrev Siggik <notifications@github.com>:
