### ISSUE TITLE
Mulighed for at vælge at skjule event fra forside, så det kun kan ses under bruger eller sted, eller evt. kun af brugeren der opretter eventet.

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#248]
Jeg er lige nu ved lokke Folkets Hus til at gå over til at bruge dukop.dk som den eksterne kalender. I den anledning er der kommet en denne idé op. Mulighed for at vælge at skjule event fra forside, så det kun kan ses under bruger eller sted, eller evt. kun af brugeren selv.

Det kan være handy, hvis man vil bruge Duk Op som sin primære kalender - Både ekstern og internt. Så kan man booke nået ind, som ikke nødvendigvis skal være super offentligt, eller måske slet ikke.

**Comment by ronan-mch** [comment]
Jeg synes at det er en god idé dog er de to ting gansk forskelligartet.

 1. Vi kan tilføj et felt der hedder **skjult** eller noget lignende til oprettelsesformularen. Når man krydser den af bliver den ikke vist på forsiden eller andre steder. Man kan dog selv se det under **Min side** og kan sende linket videre til andre. Dvs. at event siden er stadig tilgængelig, bare ikke fremhævet på nogle måde. Vi kunne evt. også indsætte en `robots.txt` regel sådan at den ikke bliver høstet af Google og lignende.

 2. En slags udkast funktion hvor man kun kan se event-en selv når man er logget ind. Dvs. at der ikke er mulighed for at dele via links. 

Jeg synes bedst om **1** da jeg synes at den er lidt mere brugbar.

**Comment by Siggik** [comment]
1 lyder godt!
