### ISSUE TITLE
udvid beskrivelsesfelt for sted når admin redigere det

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#249]
![screenshot from 2015-11-26 20 43 59](https://cloud.githubusercontent.com/assets/7570153/11429913/aec4ab6e-947e-11e5-9036-ffeb26f15e86.png)

Bare for mere luksus:)

**Comment by Siggik** [comment]
og ekstra nice kunne være mulighed for linje skift og link i tekst:)

**Comment by ronan-mch** [comment]
det er super nemt. det gøre jeg.
