### ISSUE TITLE
Manglene ugedage på steders egne sider

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#253]
Ret vigtig.

F.eks. her: https://dukop.dk/locations/49?locale=da

Derudover kunne være fedt at få steders sider shinet op generelt. Evt. udfra samme skabelon som forsiden får snart? Måske med mulighed for billede og links i beskrivelsesteksten hvis det blev helt vildt? :)

**Comment by ronan-mch** [comment]
Hej, er det her tilstrækkelig?

![location](https://cloud.githubusercontent.com/assets/1145457/12462601/7fe3d510-bfbf-11e5-977a-1033e1cadf8c.png)

**Comment by Siggik** [comment]
Det er glimrende! 

Lige på screenshottet ser det dog ud til at klokke slettet ikke står længere ud en resten af teksten? 

Og ja, billede er bare en idé. Ikke vigtigt.
