### ISSUE TITLE
Lidt idéer og forslag i forhold til layoutet til forsiden:

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#256]
Lidt idéer og forslag i forhold til layoutet:til forsiden

1) Oversigten over de faste events blir inddelt i de 7 uge dage og ikke i hver aktivitet som det er lige nu på staging. Fordi: Der er allerede så mange faste events, at jeg tror det er den eneste måde at få et overblik.  Måske er der allerede kommet så mange events. at der kun skal være den nuværende og den næste dag der er udfoldet og så kan man trykke på en kommende uge dag for at se de faste events på den? Eller hvordan kan man gøre det?

2) Den nuværende lange liste "Hele kalendere" blir sat til default ikke at vise de faste aktiviterer. Den er allerede nu ret umulig at finde rundt i. De fede unikke events forsvinder i stemmesang og kickboksing, Så kan man med tiden evt. lave en sortering mekanisme som er at vise faste event. Slå til og fra. Måske lidt a la knappen øverst til venstre her: http://b.dryicons.com/files/graphics_previews/VECTOR-FREE-ON-OFF-BUTTON.jpg

3) Som vi talte om sidst med Lars, så mangler den lange liste generelt lidt mere styling. Måske skal der tænkes i en uge opdeling, så man nemmere fatter hvad der sker hvornår.  Eller man kunne skrive "Nu på fredag" på de begivenheder som er i samme uge....

4) Måske skal det hede Højde punkter i den kommende tid: istedet for kun "Den kommende tid"? Eller er det for langt?

**Comment by Siggik** [comment]
til punkt 3 kunne der tilføjes at flere synlige tekstlinjer når eventen blir foldet ud. Måske 5? Og at man kan se hvillen bruger der har oprettet.

**Comment by ronan-mch** [comment]
Mht 2 : var det ikke bedre bare at skjule de faste ugentlige events helt fra kalender visningen? De bliver nu vist på højre siden efter dag, er det ikke fjollet at have dem begge steder?

**Comment by Siggik** [comment]
Jo, det andet er i hvert fald bare en nice feature, som ikke er vigtig og måske bare fjollet.

**Comment by ronan-mch** [comment]
Hej Sigurd, jeg har lavet det der med opdeling efter ugedage og så fjernet de faste fra kalenderen ellers. Prøv at se her: http://thawing-dawn-8343.herokuapp.com/?locale=da

**Comment by Siggik** [comment]
Det ser godt ud! Den er ved at være klar til offentliggørelse? Jeg tænker det kunne være fedt at se hvordan den ser ud med de rigtige events! Så kan smårettelser komme til når vi kan se hvordan det ser ud?

**Comment by ronan-mch** [comment]
Hvis du har tid til det må du gerne oprette nogle flere og slette de dummies på test siden, jeg har startet på det men kom ikke så lang. Det er desværre ikke ligefrem at kopiere produktions databasen til test serveren.

**Comment by Siggik** [comment]
Ja, men tænkte egentlig om den nye udgave kunne lægges på dukop.dk? Synes det ser flot ud og kan ikke se nogle store mangler. Mangler der nået essentielt?

**Comment by ronan-mch** [comment]
Nå ok, det kan jeg godt prøve, så kan vi altid rulle tilbage hvis vi opdager noget grusomt. Det eneste kritisk udestående som jeg kan komme i tanke om er den der affix dims, det kan jeg prøve at nå i aften. Jeg ved ikke om @larsgaardsoe er enige?
