### ISSUE TITLE
Måske en kategori for aktioner? 

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#257]
En Stor Mellemfinger Imod Den Nye Skolereform skrive rpå betatesten: 

Måske en kategori for aktioner?

**Comment by Siggik** [comment]
Det tænker bare at jeg gør nu med min admin bruger?

**Comment by Siggik** [comment]
Jeg gjorde det nu. og lavede et midlertidigt svar på betatest eventet.

**Comment by ronan-mch** [comment]
Fedt, ja det er mening at admin skal tage sig af kategorier osv.

søn. 6. dec. 2015 22.22 skrev Siggik <notifications@github.com>:

**Comment by ronan-mch** [comment]
Der er også en anden der skriver noget om handicap adgang på tråden..

man. 7. dec. 2015 06.35 skrev Ronan McHugh <mchugh.r@gmail.com>:

**Comment by Siggik** [comment]
Ja, det havde jeg overset. Jeg tænker at det kan skrives ind i beskrivelserne af steder?

**Comment by ronan-mch** [comment]
Ja. Jeg tænkte også at man kunne lave en Ja/Nej felt i lokationerne og så
kunne man vise en lille ikon for at fortælle om eventen har handicappede
adgang.

**Comment by Siggik** [comment]
hmm, ja, et problem jeg kan se er at der f.eks. i Ungeren og Folkets er adgang med kørestol i stuen men ikke højere op. Hvordan kan det inkorperes?

**Comment by ronan-mch** [comment]
jeg tænkte på det samme. Man kunne vel lave en lokation for hvert sted, som
man har gjort med sportshallen i Folkets. Ellers kunne man gøre adgangs
information tilgængelig fra event side, så man kunne se de forbehold der nu
er.

2015-12-07 12:17 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
jeg tror det sidste er den bedste mulighed. Der er forvirrende, hvis der blir for mange lokationer for det samme sted.
