### ISSUE TITLE
Group regular events by category

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#261]

**Comment by ronan-mch** [comment]
Another possibility is to group them by week day - see #256

**Comment by Siggik** [comment]
Det kunne også både være dag og kategori...

**Comment by ronan-mch** [comment]
Jeg prøvede faktisk med dag sortering i går. Jeg synes den fungerer meget
fint bortset fra de tømme dage skal undlades. Den kan ses nu på staging
serveren.

lør. 19. dec. 2015 10.41 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
ja, det gør det! Listen kunne dog godt blive ret lang. Måske skal hvert event fylde lidt minde, Men måske er det også i orden at "kommende begivenheder" kommer til at indeholde mere end 3 begivenheder. Lige nu er der på staging måske plads til 5.

**Comment by ronan-mch** [comment]
De enkelte serier skal helt klart fylde mindre, så kan vi begrænse antallet
til 3 per dagen og skjule de andre under en Se mere link. De skal også
sorteres efter kategori under dagene. Jeg synes ikke at der skal være for
meget mere promoverede, da vi risikerer at folk slet ikke ser resten af
kalenderen. Jeg arbejder videre med det hen over ferien og tjekker ind med
Lars når han har tid.

lør. 19. dec. 2015 12.37 skrev Siggik <notifications@github.com>:
