### ISSUE TITLE
calendar titles should link straight to event page

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#264]
get rid of dropdown effect

**Comment by Siggik** [comment]
Ok, hvad er årsagen til det? 

Er tanken at lade noget at beskrivelsesteksten stå fremme under overskriften?(tænker jeg umiddelbart gir mest meining) Eller kun at have overskriften for eventet på forsiden?

Måske er det helt cool. Men jeg og måske andre har nok lidt føelser liggende i den funktion, da den stammer helt tilbage fra en af de første brainstorms om layout:)

**Comment by ronan-mch** [comment]
Min tanke var at den funktion er for at give brugeren en hurtig overblik.
Men i den ny design får man overblikket fra den øverste panel. Desuden er
det i det hele taget lidt underligt at man skal klikke to gange for at
komme til den detaljeret visning. Det er ikke noget man ser særlig tit på
nettet (i stedet for plejer man at klikke på en titel som også er et link)
og derfor potentielt forvirrende for brugere. Der er også nogle performance
fordele ved at fjerne funktionaliteten. I det hele taget er der mange
argumenter for at fjerne det. Vi prøver det nu i vores redesign branch og
ser hvordan det går.


2015-12-07 23:33 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Helt sikkert! Jeg glæder mig til at se resultatet:)

**Comment by Siggik** [comment]
Bare lidt bruger feedback. Da vi prøvede at stresteste siden i går til mødet, var der en som roste layoutet pga. udfold muligheden. Og folk istemte at det var rart ikke med det samme, at blive sendt videre til et nyt vindue. 

Lad os forstætte som planlagt. Men ville bare dele info, så kan vi have det med i overvejelserne når vi evaluere det nye design.

**Comment by ronan-mch** [comment]
ok tak, den er på om 5

2016-01-05 21:58 GMT+01:00 Siggik <notifications@github.com>:
