### ISSUE TITLE
layout feedback fra Sigurds ven

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#270]
Bare for at dele og til evt. Inspiration: 

dukop.dk

fint med https!!

fint med Bootstrap, det gør designet meget nemmere og overskueligt

teksten kan sagtens være lidt større, for os gamle :)

tjek farve-kontrast i “hamburger”menu  ved små skærme: det grå mod den “blå” baggrund passer ikke/er forvirrende

Ingen problem med hvid baggrund men logoet kunne sagtens have mere farve

Aktivitetsliste i tabelform er mere gennemskueligt hvis rækkerne får to farver skiftevis
http://getbootstrap.com/css/#tables-striped

det kan hjælpe også de her klasses: http://getbootstrap.com/css/#tables-contextual-classes

**Comment by ronan-mch** [comment]
hvad betyder aktivitetslisten her? listen på forsiden?

**Comment by Siggik** [comment]
Ja, jeg tror også han menerlisten på forsiden.
