### ISSUE TITLE
fejl der dukker op jævntligt den 2. januar...

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#275]
![screenshot from 2016-01-02 13 07 42](https://cloud.githubusercontent.com/assets/7570153/12074404/0ff7842a-b152-11e5-868e-8f588dd376ad.png)

Men som efter et refreash af siden forsvinder igen...

**Comment by ronan-mch** [comment]
> Men som efter et refreash af siden forsvinder igen...

Så er det ikke en bug i koden men at serveren løber tør for memory og slukker for forespørgslen. Log filerne bekræfter at der kommer en masse reaped fejl:

> E, [2016-01-02T23:01:49.865415 #25303] ERROR -- : reaped #<Process::Status: pid 30456 SIGKILL (signal 9)> worker=0
I, [2016-01-02T23:01:49.884715 #30468]  INFO -- : worker=0 ready
E, [2016-01-02T23:03:12.012124 #25303] ERROR -- : reaped #<Process::Status: pid 30468 SIGKILL (signal 9)> worker=0
I, [2016-01-02T23:03:12.031676 #30592]  INFO -- : worker=0 ready

Og htop viser at `Mem` og `Swp` er fuld beskæftiget. Jeg tror vores bedste løsning er at flytte over til den nye server snarest muligt. Det kræver dog en del opsætnings arbejde og @benjaoming har ikke tid. Jeg venter på adgang til serveren fra ham og indtil der prøver jeg at diagnosticere problemet yderlige.

**Comment by Siggik** [comment]
OK.

**Comment by ronan-mch** [comment]
jeg prøver at skifte vores application server ud med en der bruger mindre memory. Jeg prøver at nå det i morgen.

**Comment by benjaoming** [comment]
Men der er jo en ny server parat....... tænker: skal vi ikke sætte det op på den i stedet? :)

**Comment by ronan-mch** [comment]
Det er en større opgave og når det kun er mig der arbejder på projektet
p.t. så tænker jeg at prioritetet må  være at få applikationen oppe og står
igen. Hvis du har tid til at kigge på det vil det være helt fantastisk.

søn. 3. jan. 2016 00.47 skrev benjaoming <notifications@github.com>:

**Comment by ronan-mch** [comment]
godt med en nyheds opdatering @Siggik

**Comment by ronan-mch** [comment]
Lukker da den værste er vist overstået.
