### ISSUE TITLE
Server migration

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#277]
- [x] dukop user
- [x] Git install
- [x] Ruby / RVM install
- [x] Postgres install
- [x] Application + dependencies install
- [x] Cron setup with `whenever`
- [x] Nginx setup
    - [x] Nginx install
    - [x] nginx.conf
    - [x] HTTPS certificate
    - [x] sites-available/dukop
- [x] Unicorn startup script
- [x]  Log rotation nginx + unicorn
- [x] Data migration
    - [x] files
    - [x] database
- [x] DNS change
- [x] Email forward from root
- [x] Ubuntu upgrades
- [x] Change ssh default port
- [x] Disable root login
- [x] Disable password login  
- [x] Correct server timezon

**Comment by ronan-mch** [comment]
tagging @benjaoming og @Siggik så I kan se hvordan det går.

**Comment by ronan-mch** [comment]
applikation kan nu køres via en lokal rails server. Næste trin er Nginx / Unicorn opsætning.

**Comment by ronan-mch** [comment]
http://blog.mailgun.com/security-guide-basic-infrastructure-security/

**Comment by benjaoming** [comment]
jeg kigger på noget db backup men det bliver bare udenom den der schedule.rb... tænker at det er nice at have en backup, der er lidt mere low-tech.

Skal vi lukke den her?
