### ISSUE TITLE
5 begivenheder under "Den kommende tid" istedet for 3

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#278]
Så der ikke er et stort tomt hvidt felt:)  Muligvis bare midltertidigt til at listen over faste ting blir lavet mindre.

**Comment by ronan-mch** [comment]
Jeg synes at 3 er meget fornuftig da hvis der bliver for mange bliver resten vel ligegyldig.  Jeg vil hellere prøve at gøre de faste til højre mindre, ved enten at shrinke nogle ting eller skjule nogle når der er for mange. Jeg er enige i at den hvide flade er suboptimal.

**Comment by Siggik** [comment]
Kan det måske bare være 5 events midlertidigt/indtil videre i "den kommende tid", indtil at listen til højre
blir gjort mindre. Hvis det er altså er rimeligt simpelt at rette. Så ser det godt ud i
vente tiden:)

**Comment by Siggik** [comment]
måske bare 4 :)

**Comment by ronan-mch** [comment]
ja, i morgen. sovetid nu.

**Comment by Siggik** [comment]
Sov godt! :) :+1:

**Comment by ronan-mch** [comment]
fixed.

**Comment by Siggik** [comment]
Ser godt ud!
