### ISSUE TITLE
Hvor er det nu jeg retter tekst på undersider? 

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#282]
Find en fejl:)
![screenshot from 2016-01-05 23 22 28](https://cloud.githubusercontent.com/assets/7570153/12129370/766828e6-b403-11e5-815c-fe572f26079e.png)

**Comment by tadoh** [comment]
English på en ny linje?

**Comment by Siggik** [comment]
Også det, men jeg tænkte på "Dup Op".

**Comment by ronan-mch** [comment]
hej, du retter ind på html-en her:
https://github.com/ronan-mch/det_sker/blob/master/app/views/pages/about.html

**Comment by Siggik** [comment]
Nu har jeg rettet det.
