### ISSUE TITLE
highlights rækkefølger problemstillinger og løsningsforslag

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#283]
Jeg skulle lige til at highlighte ID-aktionen, men fattede så at den vil kom til at ligge øverst og fucke op med kronologien i "den kommende tid" sektionen. Som vil virke skørt.

- Enten mulighed for at vælge hvor highlight skal ligge. Øverst eller nederst i listen.

- Eller en regl om at den interne kronologi bestemmer hvor begivenhederne ligger i "den kommende tid" sektionen og ikke hvilken, der er blevet highlightet først som det er nu.

**Comment by ronan-mch** [comment]
jeg synes at highlights skal sorteres efter kronologisk rækkefølge. vi
kunne evt. vælge at give dem som er "promoveret" en særlig farve så man kan
se hvorfor de ligger der.

2016-01-05 23:30 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Enig, og go idé med farve og evt en tekst a la: "Promoveret af redaktionen" eller "Fremhævet af redaktionen"

**Comment by tadoh** [comment]
+1

**Comment by ronan-mch** [comment]
fixed.

**Comment by Siggik** [comment]
Så hvis jeg f.eks. highlighter id aktion nu, så ligger den sig i bunden af "kommende begivenheder" og tager pladsen fra fredsbevægelses forslaget?

**Comment by ronan-mch** [comment]
Ja

fre. 8. jan. 2016 01.11 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
cool. Det virker!
