### ISSUE TITLE
www before links doesn't work

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#284]
Probably a known issue. Is there a way to fix it? I am assuming most people would write fx www.dukop.dk rather than https://dukop.dk

**Comment by ronan-mch** [comment]
Sorry, it's my bad, caused by the name I chose when I registered the SSL
certificate. I think it can be fixed by re-registering the certificate (and
probably paying for the privilege) but I honestly don't want to add it to
my list right now. There's already tons of things to do.

ons. 6. jan. 2016 15.08 skrev tadoh <notifications@github.com>:

**Comment by Siggik** [comment]
Hej Ronan, meget fair. Du gir den virkelig gas de her dage! Måske kan man lokke @benjaoming til at stå for det? Jeg vil gerne ligge ud til at vi forhåbentligt har penge efter den 30. januar..

**Comment by tadoh** [comment]
That's cool. Maybe I can try to get Benjamin to do a one off intervention after he has come back and has helped moving the server :)


-------- Original message --------

**Comment by benjaoming** [comment]
Noget er galt med SSL-certifikatet, det virker ikke for www.dukop.dk

Det burde dog ikke være et problem hvis vi forwarder http://www.dukop.dk ->
https://dukop.dk

Det gør vi også:

```
Resolving www.dukop.dk (www.dukop.dk)... 212.224.123.154
Connecting to www.dukop.dk (www.dukop.dk)|212.224.123.154|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://dukop.dk/ [following]
```

Det fungerer i Chromium og i Firefox fungerer det også, hvis man faktisk
sletter sin cache eller bruger en private session.

**Comment by tadoh** [comment]
@benjaoming I need to make sure I understand this. I can see that using a private sessions does the trick, but how to change this from my normal session? Wouldn't other users also have the same issue when typing www.dukop.dk?

We also had the same issue when we wrote www.dukop.dk in a facebook update. The link led to the untrusted connection page...

**Comment by benjaoming** [comment]
> Wouldn't other users also have the same issue when typing www.dukop.dk?

The server does the right thing, I don't know why browsers keep the 'www' in the address. We need to get a certificate that allows for both `dukop.dk` and `www.dukop.dk`.

I can get one tonight.

**Comment by tadoh** [comment]
Super!

Den 29-01-2016 kl. 15:39 skrev benjaoming:

**Comment by dotnetCarpenter** [comment]
@benjaoming hvorfor ikke bruge dns redirect fra www -> naked domain? Så spare du en roundtrip.

**Comment by benjaoming** [comment]
Nåhja for søren @dotnetCarpenter det var da en god ide! :D

**Comment by benjaoming** [comment]
Er ændret... vent på DNS refresh

**Comment by dotnetCarpenter** [comment]
weird - @benjaoming kan du forklare hvad der sker her?
http://tools.pingdom.com/fpt/#!/c4xDAm/https://www.dukop.dk - ingen redirect
http://tools.pingdom.com/fpt/#!/eIhCzI/http://www.dukop.dk - redirect til naked https
http://tools.pingdom.com/fpt/#!/73SRS/dukop.dk - redirect til https
http://tools.pingdom.com/fpt/#!/bnvGHe/https://dukop.dk - ingen redirect

Det er dårligt for SEO. Google kræver faktisk en `<link rel="canonical" href="https://dukop.dk/page-1">` på hver side for at ikke at se www.duk.op og dukop.dk som 2 forskellige sites.
https://support.google.com/webmasters/answer/139066?hl=en
Hvad med at DNS redirect til https://dukop.dk, så spare i også et ny certifikat.

Men så er der kun et problem tilbage... http://serverfault.com/questions/408017/why-does-heroku-warn-against-naked-domain-names

**Comment by benjaoming** [comment]
@dotnetCarpenter har lavet et CNAME, det virker.

Men httpS://www.dukop.dk vil ikke virke før vi har nyt cert, men vi har forhåbentlig ikke noget sted, der redirecter hertil længere.

**Comment by dotnetCarpenter** [comment]
Hvorfor ikke bare DNS redirecte httpS://www.dukop.dk til  httpS://dukop.dk. Mener jeg har gjort det engang den anden vej.

**Comment by ronan-mch** [comment]
i thought we did that before - did we forget to move that bit of the config
over?

2016-01-30 15:47 GMT+01:00 Jon Ege Ronnenberg <notifications@github.com>:

**Comment by dotnetCarpenter** [comment]
@ronan-mch I think it's better to use DNS for the routing, to save the extra roundtrip a server redirect requires. I think I made an ALIAS for the subdomain redirection, when I was setting up something similar a while back. Which DNS provider do you use? Do you have email on dukop.dk (MX record)?

**Comment by dotnetCarpenter** [comment]
@ronan-mch @benjaoming @tadoh god fest i aften forresten!

**Comment by dotnetCarpenter** [comment]
@benjaoming du har ret. Du skal enten bruge et wildcard cert eller 2 cert, som også selv siger. My bad.

**Comment by benjaoming** [comment]
DNS foregår uanset TCP port, dvs. det er uanset om det er https eller http. Forskellen er, at SSL-handshake foregår på IP-niveau og du ikke kan lave en redirect via et ugyldigt certifikat. Så hvis folk går ind på https://www.dukop.dk, sker følgende:

1) Domæne slås op via DNS og de får IP
2) SSL handshake, som fejler, fordi cert ikke er gyldigt.
3) Hvis man laver en undtagelse: Http forespørgsel på host:www.dukop.dk og nginx laver 403 redirect til dukop.dk

det var en fed fest :)

**Comment by dotnetCarpenter** [comment]
@benjaoming 403 - http://httpstatusdogs.com/403-forbidden

**Comment by benjaoming** [comment]
Sorry, jeg mente 301 :)

**Comment by tadoh** [comment]
Opdagede lige at det her er stadig et issue... kan den fixes? Der står www på alle vores plakater...
@benjaoming @dotnetCarpenter @ronan-mch

**Comment by ronan-mch** [comment]
SSL Certifikatet er ved at udløbe så jeg regner med at lave ordne det der.
Og det var altså dukop.dk langt inden plakaterne blev lavet ;)

Den tor. 14. apr. 2016 17.02 skrev tadoh <notifications@github.com>:

**Comment by ronan-mch** [comment]
Nu hedder det https://www.dukop.dk.
