### ISSUE TITLE
logoet skal linke til forsiden

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#286]
Uden at tænke over det trykker jeg selv hele tiden på det, for at komme tilbage til forsiden. Da jeg viste siden til en ven i går, klikkede han fem gange på loget indtil jeg fortalte ham at han skulle trukke på "kalender" knappen..

**Comment by ronan-mch** [comment]
fuck hvor dumt, det retter jeg.

2016-01-08 12:18 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
nice
