### ISSUE TITLE
Gentagene events uden flere gentagelser optræder i kalenderen

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#288]
f.eks.: https://dukop.dk/event_series/26?locale=en

https://dukop.dk/event_series/4?locale=en

**Comment by Siggik** [comment]
og jeg kan ikke slette Byens Radio eventet som admin: https://dukop.dk/event_series/26?locale=da . Kun aflyse, men det skal fjernes helt. Kan du slette det @ronan-mch ?

**Comment by Siggik** [comment]
NU prøvede jeg at "aflyse" eventet, men fik denne fejl melding: 
"We're sorry, but something went wrong.

If you are the application owner check the logs for more information." kl 23.03.

**Comment by ronan-mch** [comment]
#292

**Comment by ronan-mch** [comment]
Sorry, jeg prøvede lige at slette den og det kan nok sagtens lade sig gøre men jeg løb lige ind i nogle andre issues med server config som jeg ikke har lyst til at kast mig ud lige nu. :sleeping:

**Comment by ronan-mch** [comment]
Et andet ting, burde man som admin kunne slette serier helt? Det indebærer at man slette alle forekomster af tilhørende events, men det er vel ok, ikke?

**Comment by Siggik** [comment]
Jo, jeg tænker at det skal man også kunne. I fremtiden ville en mulighed for at skjule et event men ikke slette helt også være godt. Så kunne man som admin hurtigt fjerne noget, men også have mulighed for at fortryde, hvis f.eks  de andre i redaktørgruppen synes det ikke skal slettes.

**Comment by Siggik** [comment]
Nu fik jeg fat i byens radio. Brugeren selv kan ikke se eventen, på deres side. De kan se det på forsiden, men ikke slette.

**Comment by Siggik** [comment]
Hej @ronan-mch,  Kan du slette de 2 serier.

**Comment by ronan-mch** [comment]
nej.

**Comment by Siggik** [comment]
Ok

**Comment by Siggik** [comment]
:)

**Comment by ronan-mch** [comment]
Nu er de væk.

**Comment by Siggik** [comment]
Sejt!

**Comment by ronan-mch** [comment]
Hej, jeg lukker den her. Lige nu viser **Faste begivenheder** alle de ugentlig events med udløbsdato i fremtiden. Det er meget enkelt logik men åbner op for at hvis en ugentlig serie sletter fremtidige events bliver den stadig vist i spalten. Indtil videre vælger jeg **ikke** at gøre noget mere ved dette problem pga. følgende overvejelser:

- 1 jeg vurderer at omfanget ikke er særlig stor, 
- 2 det vil gøre database query-en væsentlig mere kompliceret at tage højde for disse få død serier og derfor forværre load tid på forsiden.
- 3 Jeg mener at administratorer nu har de rigtige værktøj til at håndtere problemet skulle det opstå igen.

I må gerne genåbne sagen hvis I er uenige med min vurdering.

**Comment by Siggik** [comment]
Det er fint. Jeg tror du har ret i at nu kan admins rette det til hvis det blir nødvendigt.
