### ISSUE TITLE
RSS feed for events

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#291]
One feed for the calendar and subfeeds for locations and users. See comments from Biveke here: https://dukop.dk/events/6?locale=da

**Comment by ronan-mch** [comment]
Det virker lidt kryptisk at skrive "de tre meste benyttede keyserver". Hvorfor ikke ligge selve nøglen oppe på siden? Jeg ser det tit rundt omkring.

**Comment by Siggik** [comment]
Jo, go pointe. Kan du ligge den op hvis jeg sender dig den eller kan du selv hente den?

**Comment by ronan-mch** [comment]
Svarer du til den rigtige issue her?

tir. 12. jan. 2016 11.22 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Nej, men på min telefon ser det ud som om at det var dig der startede:) Men under alle omstændigheder. Min kommentar var om den offentlig PGP nøgle. Hvor skulle sig have svaret?

**Comment by ronan-mch** [comment]
på Pull Request #289, men det er lige meget jeg blev bare forvirret. du må gerne tilføje den til din PR, så merger jeg når det er.

**Comment by Siggik** [comment]
@tadoh har du snakket med Biveke? Jeg tænker at det måske er Icalender standard de har brug for og ikke RSS? Eller de kan også vælge den meget lavtekniske løsning som Folkets benytter lige nu: www.folketshus.dk/kalenderen/

Jeg forstår ikke helt hvordan RSS skulle virker?

**Comment by tadoh** [comment]
Jeg har forslået Biveke en løsning lige á la folkets (dog med fokus på brugeren "IF" og ikke location), ved ikke hvorfor hun snakker om RSS. Måske @larsgaardsoe ? Du ved bedre end mig hvordan det står til med IF's hjemmeside.
Hendes sidste mail: 

Jeg har spurgt ham på hjemmesiden i feedback-feltet - og det siger han, at han gerne vil gøre, så alt er fint. 
Ja, lad os tale om det senere. Jeg fik det testsite, som Lars har lavet, tilsendt igår.

**Comment by ronan-mch** [comment]
Hej,

jeg foreslog RSS fordi jeg mener at det er bedre egnet til integration med
en eksterne hjemmeside, men det kunne sagtens være at jeg tager fejl. Som
jeg forstår iCal så laver man en .ics fil med event data som man så kan
import ind til sin egen kalender en gang, men hvis der kommer nye events så
skal man import sådan en fil igen. Er det helt misforstået?

Ronan

2016-01-12 21:22 GMT+01:00 tadoh <notifications@github.com>:

**Comment by Siggik** [comment]
Jeg er slet ikke nogen ekspert. Men har lidt erfaring fra at brugt wordpress og google calender. Her skulle vi impoterer en ical feed til widgeten som beskrevet her: https://en.support.wordpress.com/widgets/upcoming-events/

Som så automatisk opdaterede når google calender blev opdateret. 

Her beskriver de drømme scenariet: "Import and Export Events

Timely offers full ics/ical support. You can import events from other calendars and offer users the ability to subscribe to your calendar.

Importing and exporting iCalendar (.ics) feeds is one of the strongest features of the All-in-One Event Calendar system. Enter an event on one site and you can have it appear automatically in another website's calendar. You can even send events from a specific category or tag (or combination of categories and tags)." Kilde: https://wordpress.org/plugins/all-in-one-event-calendar/ 

Men kender ikke RSS særlig godt. Udover at have abonnneret på nyheder.  Når jeg googler det kommer det frem at google dropper at bruge RSS til kalendere: https://feed.mikle.com/support/google-calendar-rss-feed/ og at det RSS typisk er til nyheder og Icalender er til kalendere: https://events.stanford.edu/about/rss

**Comment by ronan-mch** [comment]
ok, i så fald så er iCal klart en bedre løsning.

**Comment by biveke** [comment]
Hej Folks
Jeg kan se at I lidt mystificerede over min forespørgsel om et feed. Forklaringen er simpel. Hvis vi får et feed, kan vi nøjes med at sætte kalenderopslag på 1 sted - nemlig på dukop.dk - og så trække vores egne opslag ind på vores side som en liste fra dukop.dk med automatisk genereret indhold. Så slipper vi for arbejdet ved at skulle lægge kalenderopslag på både på vores egen side og hos dukop.dk. Jeg er ikke sikker på, at vi er superinteresserede i iCal. Et helt ordinært feed uden alt muligt i-halløj ind over er lettere at arbejde med, dvs. mere flexibelt.

**Comment by biveke** [comment]
Feeds-modulet fungerer nu så fint på Drupal 8, at man kan trække lister ind fra andre sites. Så I må meget gerne gå igang med at sætte et feed op på Duk Op. Det vil være en kæmpe hjælp for os, hvis vi kan trække vores kalender ind på IFs nye hjemmeside på den måde.

**Comment by ronan-mch** [comment]
Hej Biveke, tak for tippet. Den er på min liste, håber at kunne nå det snart.

**Comment by biveke** [comment]
Superfedt, Ronan!

**Comment by ronan-mch** [comment]
Sample output her baseret på [RSS 2.0 docs](http://cyber.law.harvard.edu/rss/rss.html):
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
  <channel>
    <title>Folkets Hus</title>
    <link>https:/dukop.dk/locations/14?locale=en</link>
    <description>Folkets Hus er Nørrebros eget samlingssted. Her kan du lære dine naboer at kende, dyrke sport, drikke kaffe, se film, lave folkekøkken, hænge ud og meget, meget mere!  Folkets Hus drives af frivillige Nørrebroere. Vi har højt til loftet og rigeligt med plads til gode ideer og lokalt engagement. Huset er brugerstyret, og vi holder jævnligt Fællesmøder, hvor vi tager stilling til, hvordan huset skal drives. Folkets Café har ÅBENT: tirsdag, onsdag, torsdag, fredag fra 10-22. Søndag fra 10-14. Kom og nyd en kaffe, te, sodavand, saft eller øl i godt selskab!</description>
    <docs>http://cyber.law.harvard.edu/rss/rss.html</docs>
    <ttl>30</ttl>
<item>
      <title>Folkets Haus</title>
      <link>https://dukop.dk/events/481?locale=en</link>
      <guid>https://dukop.dk/events/481?locale=en</guid>
      <description>Folkets Haus er Folkets Cafés elektroniske lounge og fælles forfest. Den anden fredag i hver måned inviterer vi til forfest med dejlig elektronisk musik (Deep House, Tech House, mm) og god stemning. Så hvorfor varme op til din fredag aften derhjemme alene - når vi kan være sammen om det?

Mere info om den enkelte arrangement følger... og mens du venter, kan du lytte til tidligere mixes fra Folkets Haus på https://www.mixcloud.com/FolketsHaus/</description>
      <pubDate>Wed, 20 Jan 2016 15:05:37 +0000</pubDate>
      <category>Party</category>
    </item>
  </channel>
</rss>
```

**Comment by ronan-mch** [comment]
Så vidt som jeg kan se fra RSS dokumentation er der ikke noget oplagt sted at ligge vigtig oplysninger som lokation og tidspunktet af en event. Der er `pubDate` feltet men det er til hvornår eventet blev oprettet og ikke hvornår det sker. Har du gjort dig nogle tanker om hvordan I vil have det? Burde det bare være med i beskrivelsen? Eller vil I have en ekstra metadata felt til det?

**Comment by dotnetCarpenter** [comment]
Du kan *extend* RSS med dine egne fields eller bruge et format der allerede er lavet: http://www.rss-tools.com/namespace-extensions.htm Måske er det nemmere for forbrugere at konsumere.

*Eksempel på custom rss format*
```xml
<?xml version="1.0" encoding="UTF-8"?>
<rss
  xmlns:duk="http://dukop.dk/rss/events"
  version="2.0">
  <channel>
    <title>Folkets Hus</title>
    <link>https:/dukop.dk/locations/14?locale=en</link>
    <description>Folkets Hus er Nørrebros eget samlingssted. Her kan du lære dine naboer at kende, dyrke sport, drikke kaffe, se film, lave folkekøkken, hænge ud og meget, meget mere!  Folkets Hus drives af frivillige Nørrebroere. Vi har højt til loftet og rigeligt med plads til gode ideer og lokalt engagement. Huset er brugerstyret, og vi holder jævnligt Fællesmøder, hvor vi tager stilling til, hvordan huset skal drives. Folkets Café har ÅBENT: tirsdag, onsdag, torsdag, fredag fra 10-22. Søndag fra 10-14. Kom og nyd en kaffe, te, sodavand, saft eller øl i godt selskab!</description>
    <docs>http://cyber.law.harvard.edu/rss/rss.html</docs>
    <ttl>30</ttl>
<item>
      <duk:startdate>2016-02-15T10:00</duk:startdate>
      <duk:enddate>2016-02-15T22:00</duk:enddate>
      <duk:location>Stengade 50, 2200 København N</duk:location>
      <title>Folkets Haus</title>
      <link>https://dukop.dk/events/481?locale=en</link>
      <guid>https://dukop.dk/events/481?locale=en</guid>
      <description>Folkets Haus er Folkets Cafés elektroniske lounge og fælles forfest. Den anden fredag i hver måned inviterer vi til forfest med dejlig elektronisk musik (Deep House, Tech House, mm) og god stemning. Så hvorfor varme op til din fredag aften derhjemme alene - når vi kan være sammen om det?

Mere info om den enkelte arrangement følger... og mens du venter, kan du lytte til tidligere mixes fra Folkets Haus på https://www.mixcloud.com/FolketsHaus/</description>
      <pubDate>Wed, 20 Jan 2016 15:05:37 +0000</pubDate>
      <category>Party</category>
    </item>
<item>
      <duk:startdate>2016-02-16T10:00</duk:startdate>
      <duk:enddate>2016-02-16T22:00</duk:enddate>
      <duk:location>Stengade 50, 2200 København N</duk:location>
      <title>Folkets Haus</title>
      <link>https://dukop.dk/events/481?locale=en</link>
      <guid>https://dukop.dk/events/481?locale=en</guid>
      <description>Folkets Haus er Folkets Cafés elektroniske lounge og fælles forfest. Den anden fredag i hver måned inviterer vi til forfest med dejlig elektronisk musik (Deep House, Tech House, mm) og god stemning. Så hvorfor varme op til din fredag aften derhjemme alene - når vi kan være sammen om det?

Mere info om den enkelte arrangement følger... og mens du venter, kan du lytte til tidligere mixes fra Folkets Haus på https://www.mixcloud.com/FolketsHaus/</description>
      <pubDate>Wed, 20 Jan 2016 15:05:37 +0000</pubDate>
      <category>Party</category>
    </item>
<item>
      <duk:startdate>2016-02-17T10:00</duk:startdate>
      <duk:enddate>2016-02-17T22:00</duk:enddate>
      <duk:location>Stengade 50, 2200 København N</duk:location>
      <title>Folkets Haus</title>
      <link>https://dukop.dk/events/481?locale=en</link>
      <guid>https://dukop.dk/events/481?locale=en</guid>
      <description>Folkets Haus er Folkets Cafés elektroniske lounge og fælles forfest. Den anden fredag i hver måned inviterer vi til forfest med dejlig elektronisk musik (Deep House, Tech House, mm) og god stemning. Så hvorfor varme op til din fredag aften derhjemme alene - når vi kan være sammen om det?

Mere info om den enkelte arrangement følger... og mens du venter, kan du lytte til tidligere mixes fra Folkets Haus på https://www.mixcloud.com/FolketsHaus/</description>
      <pubDate>Wed, 20 Jan 2016 15:05:37 +0000</pubDate>
      <category>Party</category>
    </item>
<!-- mange flere items -->
  </channel>
</rss>
```

https://schema.org/ har muligvis også nogle formater og har support fra Google, Microsoft, Yahoo og Yandex.

**Comment by ronan-mch** [comment]
ja, jeg er ikke meget for at opfinde min egen metadata format, hvis jeg
skulle indsætte nogle andre felter vil det nok være xCal eller måske
schema.org  som du siger. Jeg tvivler dog på at brugeren vil have disse:
som jeg forstår fra forslaget så vil de have så simpel data som muligt. Jeg
går derfor ud fra at de ikke vil have custom felter med.

2016-02-18 14:57 GMT+01:00 Jon Ege Ronnenberg <notifications@github.com>:

**Comment by biveke** [comment]
Det vigtigste er, at modtageren kan suge data ind i en hvilken som helst side. De fleste, der typisk vil have behov for at trække en liste med data fra Duk Op, er nok ikke programmører, men laver bare et eller andet i et eller andet CMS system, fx Drupal eller Wordpress. Derfor skal det helst være så let at modellere som muligt for modtageren. Det får måske den konsekvens, at dem, der trækker Duk Op-data ind på deres egne sites, bliver nødt til at helgardere ved også at lægge begivenhedens dato ind i "description"-feltet... Men hellere det end et særligt custom-felt, som folk alligevel ikke rigtigt kan bruge. 

Ergo - rå standardformater, som kan bruges til hvadsomhelst og er helt uden avanceret præformattering, custom-felter og i-cal-halløj, vil være at foretrække. Så har modtageren noget at lege med. I hvert fald til en start.

**Comment by dotnetCarpenter** [comment]
OK, det her ser ud til at väre formatet: http://essfeed.org/
Rails gem: https://github.com/essfeed/rails-ess
Wordpress plugin: https://wordpress.org/plugins/events-manager-ess/
Kan ikke finde et drupal plugin men der er et php library, så det er muligt at udvikle ét drupal plugin uden at starte fra ingenting: https://github.com/essfeed/php-ess

**Comment by dotnetCarpenter** [comment]
Ellers ser det ud til at et standard RSS/ATOM feed med tider og steder i beskrivelsen er vejen frem... :-1:

**Comment by dotnetCarpenter** [comment]
Hvis Drupal 8 support er et **MUST**... ser det sort ud.
~~Hmm.. jo mere jeg kigger på det her ser det ud til at [iCal](http://tools.ietf.org/html/rfc5545) vejen frem.
Google calendar generere end `.ics` ved request. Almindelige http headers (Last-Modified) kan bruges ved synkronisering og der findes både et [library](https://github.com/icalendar/icalendar) og en [artikel om ical support i rails ved brug biblioteket](http://blog.greenfieldhq.com/2015/04/10/iCal-subscriptions-with-ember-and-rails/).
Wordpress: [artikel](https://en.support.wordpress.com/widgets/upcoming-events/) og [plugins](https://wordpress.org/plugins/tags/icalendar)
Drupal 8: support alle ical formater ser dårlig ud.~~

**Comment by biveke** [comment]
Jon - det ser ikke spor sort ud. Jeg har testet modulet Feeds til Drupal 8 og man kan sagtens trække et feed fra fx dr.dk på det udviklingsstadie, hvor Feeds er nu. Jf. den kommentar, som jeg lagde ind i denne tråd for to dage siden.

**Comment by dotnetCarpenter** [comment]
Hej @biveke. Har du et eksempel feed url fra DR?
Jeg har lige hentet RSS feed'et fra kultur sektionen: http://www.dr.dk/nyheder/service/feeds/kultur

Der findes [ikke noget field for lokation, startdato eller slutdato i RSS](https://validator.w3.org/feed/docs/rss2.html#hrelementsOfLtitemgt). Så hvis [dukop.dk](https://dukop.dk/) har et RSS feed mangler den information. Det er måske en udfordring at lave en kalender uden dato'er på IF's side. DR har nogle custom felter, bland andet `<DR:ChannelName>Historie</DR:ChannelName>` på items og `<DR:Year>2016</DR:Year>` på channel. Hvordan ser de felter ud via Feeds til Drupal 8?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet title="XSL_formatting" type="text/xsl" href="http://www.dr.dk/nyheder/htm/service/rss/rssfeed.xsl"?>
<?xml-stylesheet title="XSL_formatting" type="text/xsl" href="http://www.dr.dk/nyheder/htm/service/channel/channelfeed.xsl"?>
<?xml-stylesheet title="XSL_formatting" type="text/xsl" href="http://www.dr.dk/nyheder/htm/service/rss/rssfeed.xsl"?>
<rss xmlns:DR="http://dr.dk/channel/2.0/modules/dr/" version="2.0">
   <channel>
      <title>Kultur</title>
      <description />
      <link>http://www.dr.dk</link>
      <DR:Year>2016</DR:Year>
      <language>da</language>
      <item>
         <guid isPermaLink="false">c30f015a-b2e8-4797-b58c-129983e0ca54</guid>
         <title><![CDATA[Virtual Reality: Drømmen om at opleve en anden virkelighed er oldgammel]]></title>
         <description><![CDATA[Nye teknologier, eksperimenterende teaterformer og anderledes udstillinger har mange gange gennem historien forsøgt at give folk en illusion af at være til stede i en anden virkelighed, påpeger historiker.]]></description>
         <link>http://www.dr.dk/nyheder/kultur/historie/virtual-reality-droemmen-om-opleve-en-anden-virkelighed-er-oldgammel</link>
         <DR:XmlImageArticle>
            <DR:ImageUri620x349>http://prod-public-files-cms-dr-dk.s3.amazonaws.com/images/article/2016/02/18/baerende.jpg</DR:ImageUri620x349>
         </DR:XmlImageArticle>
         <pubDate>Thu, 18 Feb 2016 19:31:00 +0100</pubDate>
         <DR:PostingGuid>c30f015a-b2e8-4797-b58c-129983e0ca54</DR:PostingGuid>
         <DR:ChannelName>Historie</DR:ChannelName>
         <DR:ChannelDisplayName>Historie</DR:ChannelDisplayName>
      </item>
<!-- mange flere items -->
```
*Hvis custom felter kan importeres via Feeds til Drupal, så er [comment-185734077](291#issuecomment-185734077) vejen frem*

**Comment by ronan-mch** [comment]
Hej, jeg tror ikke der er behov for yderligere afklaring, indtil videre
laver jeg bare råt rss som bestilt, hvis IF senere finder ud af de vil have
noget andet så laver jeg det til det tidspunkt. Jeg har nu lavet det til
lokationer, jeg laver det til brugere hurtigst muligt og sætter den op på
vores test side så I kan se på det der.

tor. 18. feb. 2016 23.26 skrev Jon Ege Ronnenberg <notifications@github.com

**Comment by biveke** [comment]
Ronan, bare gør det så enkelt for dig selv som muligt. Så kan vi altid gøre det mere avanceret, når udviklerne på Drupal 8 er kommet videre med Feeds-modulet. Det vil være rigtig fint bare at få et simpelt feed i første omgang.

**Comment by ronan-mch** [comment]
Hej Biveke, jeg har lagt en sample op på vores test site:

Her ser du en [feed for en bruger](http://thawing-dawn-8343.herokuapp.com/users/30.rss?locale=da)

og her ser du en [feed for en lokation](http://thawing-dawn-8343.herokuapp.com/locations/15.rss?locale=da)

Lad mig lige ved om det duer.

**Comment by biveke** [comment]
Med den opsætning, som jeg hidtil har lavet (og som sikkert kunne være bedre...) blev flg importeret:

**Feed bruger items**
Etiket	Imported	GUID	URL
monthly test	1 minut siden	http://thawing-dawn-8343.hero…	http://thawing-dawn-8343.hero…
weekly test	1 minut 1 sek. siden	http://thawing-dawn-8343.hero…	http://thawing-dawn-8343.hero…
Salina Yoga	1 minut 1 sek. siden	http://thawing-dawn-8343.hero…	http://thawing-dawn-8343.hero…
Hipster test	1 minut 1 sek. siden	http://thawing-dawn-8343.hero…	http://thawing-dawn-8343.hero…

Eksempel på et enkelt items indhold: 
monthly test
Indsendt af Anonym (ikke efterprøvet) den lør, 02/20/2016 - 11:31
conga beach, man d. 18. apr 10:00 the bleep happening here?

**Feed lokation items**

Etiket	Imported	GUID	URL
Salina Yoga	9 minutter 8 sekunder siden	http://thawing-dawn-8343.hero…	http://thawing-dawn-8343.hero…

Dette items indhold:
Salina Yoga
Indsendt af Anonym (ikke efterprøvet) den lør, 02/20/2016 - 11:28
Folkets Hus - Sportsrummet, ons d. 23. mar 17:00 Bendy bendy

**Comment by biveke** [comment]
Visningen af hipster-testen fra Feed Bruger er måske mere sigende for, hvad der faktisk kommer med: 

Hipster test
Indsendt af Anonym (ikke efterprøvet) den lør, 02/20/2016 - 11:31
that place, fre d. 26. feb 20:45 Lo-fi cronut XOXO semiotics farm-to-table, scenester shabby chic try-hard knausgaard health goth sustainable. PBR&B messenger bag put a bird on it, cray intelligentsia chartreuse bitters four dollar toast disrupt tacos. Artisan gochujang organic keytar hashtag truffaut offal. Single-origin coffee flannel cray iPhone skateboard hammock banjo health goth readymade artisan, chicharrones chillwave before they sold out man bun small batch. Shabby chic affogato man bun pour-over. Butcher literally readymade, vice pug echo park stumptown kogi single-origin coffee pabst. Hashtag organic aesthetic ethical gochujang dreamcatcher. Slow-carb before they sold out vegan aesthetic master cleanse pork belly. Aesthetic disrupt hammock green juice church-key, migas typewriter try-hard wolf selfies marfa. Vice man bun austin YOLO. Jean shorts locavore letterpress normcore, viral brunch sustainable. Fingerstache organic fashion axe irony, pork belly tote bag pitchfork twee tumblr schlitz. Street art celiac pork belly chicharrones, health goth salvia normcore. Tacos whatever stumptown cliche, vegan photo booth man bun blue bottle hashtag. Tumblr skateboard tofu, sriracha master cleanse you probably haven't heard of them microdosing bespoke vice. Tacos pug tumblr lo-fi green juice. Venmo blue bottle chicharrones PBR&B next level, literally listicle ugh roof party truffaut pork belly. Neutra wayfarers twee quinoa. Retro listicle occupy flannel disrupt, authentic kinfolk. VHS pop-up fingerstache, fixie 3 wolf moon PBR&B yr four dollar toast DIY cardigan fanny pack. Deep v normcore jean shorts thundercats, blue bottle drinking vinegar seitan vinyl DIY.

**Comment by biveke** [comment]
Der er dog et problem med linket til det enkelte item inde på Duk Op/den side som du prøver at koble feedet til. Og det link fungerer eller upåklageligt når jeg fx tester på dr.dk's kultur-feed, så modulet kan godt linke direkte til et item på "afsender-siden" (fx DR/event eller Duk Op/event) fra drupal-sitet.

**Comment by ronan-mch** [comment]
Hej, hvad fejler linket? Og hvor kommer det der indsendt af anonym fra?

lør. 20. feb. 2016 12.41 skrev biveke <notifications@github.com>:

**Comment by biveke** [comment]
Indsendt af anonym kommer fra min opsætning af drupal. Det skal du ikke tage dig af. Jeg har fjernet det igen. Hipster-testens link er fx dette: http://thawing-dawn-8343.herokuapp.com/locations/30?locale=da

**Comment by ronan-mch** [comment]
Ok, det tror jeg er min fejl. Jeg retter den snarest.

lør. 20. feb. 2016 13.58 skrev biveke <notifications@github.com>:

**Comment by ronan-mch** [comment]
Den skal gerne være rettet nu, prøve at tjekke linkerne igen.

**Comment by biveke** [comment]
Ja, den er fixet, oven i købet med implicit link. Smukt!

**Comment by ronan-mch** [comment]
det var godt, især når jeg ikke helt ved hvad implicit link betyder her...

**Comment by ronan-mch** [comment]
Den er nu i produktion. Se for eksempel på [IF brugerens side](https://dukop.dk/users/28.rss?locale=da).

**Comment by biveke** [comment]
Jaaaaaah

**Comment by Siggik** [comment]
Ser godt ud. Skal bruger og steder siderne ikke have en RSS-knap?

**Comment by ronan-mch** [comment]
det kunne godt være at det var et god måde at gøre det mere synligt på. Der er allerede en link til rss udgaven i disse sider så en bruger med en RSS knap aktiveret i deres browser vil godt kunne se det men en knap vil selvfølgelig gøre det synligt for alle de andre. Det eneste jeg tænker er at der måske ikke er stor efterspørgsel for RSS blandt almindelig brugere. I dette tilfælde udstiller vi RSS til en maskinelt bruger, men er det noget som folk vil bruge til deres egne kalender?

**Comment by biveke** [comment]
Man kan sige, at man lige så godt kan udstille sin ekstra feature for en almindelig bruger, nu hvor du har gjort et så stort arbejde med overhovedet at lave en feed funktionalitet. Men RSS er selvfølgelig ikke toppen af poppen længere, så du har nok ret i, at de fleste såkaldte "almindelige brugere" ikke vil abonnere på opdateringer fra et sted eller en bruger via et feed. Selvom det egentlig er lige så smart som at få SMS-notifikationer, hvis det fx er et sted man kommer meget eller en organisation, hvis arrangementer kan gerne vil følge...

**Comment by tadoh** [comment]
Enig med biveke. Kun få der vil bruge det, men lad os give dem mulighed for det, nu at du har lavet arbejdet. 

Godt gået i øvrigt :)

-------- Original message --------

**Comment by ronan-mch** [comment]
ok, det gøre jeg. jeg burde egentlig også lave en til forsiden...

biveke, er du sød at skrive når du integrerer feed-en i IFs hjemmeside? Jeg
vil gerne se det når det er...

2016-03-02 8:07 GMT+01:00 tadoh <notifications@github.com>:

**Comment by biveke** [comment]
Ronan, jeg kan give dig midlertidig adgang, så du kan se det allerede nu. Send mig en mail. Nicola har adressen.

**Comment by tadoh** [comment]
Har sendt bivekes mail til Ronan via mail.

Den 02-03-2016 kl. 21:17 skrev biveke:
