### ISSUE TITLE
Allow admins and owners to delete event_series with all events

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#293]
make sure to give them a warning first. see #288

**Comment by ronan-mch** [comment]
@Siggik - jeg har lagt en ny udgave meg nogle af disse ændringer op på den nye maskine. Det virker fint for mig men du må gerne lige dobbel tjek det for mig. Hvis du er tilfreds så opdaterer jeg app-en i aften.

**Comment by Siggik** [comment]
Cool Adressen til den nye maskine er? Du har hvis dtel den før, men kan ikke lige finde hvor.

**Comment by ronan-mch** [comment]
i din mail...

**Comment by ronan-mch** [comment]
it's alive! hedder mailen, den kom i lørdags.

**Comment by Siggik** [comment]
Jeg slettede hele serien Byens Radio ved at trykke "slet serien". Det virkede fint! Men hvad er forskellen på at "slette serien" og slette alle forekomster? 

Det så sådan her ud: 
![screenshot from 2016-01-13 21 45 16](https://cloud.githubusercontent.com/assets/7570153/12307415/68f384fc-ba3f-11e5-9a64-c887afa2c102.png)

Den engelske tekst, der er min browser der spørg om det?

**Comment by ronan-mch** [comment]
ja det er en browser ting når en side bliver ved med at oprette alert
boxes. forskellen mellem at slet forekomster og serien er at serien som et
objekt stadig findes i systemet efter man har slettet alle forekomster. Man
kan godt opdatere den og oprette flere forekomster hvis man vil det.

**Comment by Siggik** [comment]
tjek.
