### ISSUE TITLE
Fix enable_comments checkbox 

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#295]
I made my event and clicked on allow comments.
I had to edit something and when I opened the event and clicked on "edit", the comment option was unchecked. This way I had to click it again to allow comments.

Shouldn't it stay on, if the user had previously decided that it should be on?

**Comment by ronan-mch** [comment]
yeah, that checkbox is fucked, same reason as the other other checkbox, but at least I know how to fix it now.

**Comment by tadoh** [comment]
:+1:
