### ISSUE TITLE
Hvis man fornyer et gentagende events inden sidste event er udløbet optræder eventsene dobbelt på serien side.

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#296]
![screenshot from 2016-01-14 09 59 40](https://cloud.githubusercontent.com/assets/7570153/12319968/16b1843e-baa6-11e5-8b78-3df7d08ffe6e.png)

**Comment by ronan-mch** [comment]
Godt fanget. Det burde være nemt at løse.

tor. 14. jan. 2016 10.03 skrev Siggik <notifications@github.com>:
