### ISSUE TITLE
No margin at the bottom of a description

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#299]
For instance here: https://dukop.dk/events/388?locale=da
The text ends very close to the edge of the browser - it would probably look better with a small margin?

Very low priority :)

(I caught myself trying to scroll down to see if there was more text, as I was not sure it ended there)

**Comment by ronan-mch** [comment]
I think that depends on your screen size. It looks different on my
(absolutely massive) work monitor.

**Comment by tadoh** [comment]
:)

I have a 13" - pretty common size I guess?

**Comment by ronan-mch** [comment]
i've always heard rumours about Italians...

**Comment by tadoh** [comment]
Right when I pressed send I figured it was a dangerous sentence...


-------- Original message --------

**Comment by ronan-mch** [comment]
but then you thought, "I'm sure Ronan's not that immature", but he is...

**Comment by tadoh** [comment]
:+1:

**Comment by Siggik** [comment]
I er sku god underholdning:)

**Comment by tadoh** [comment]
Selvfølgelig er vi det, med en 13"...

**Comment by tadoh** [comment]
Ja okay jeg forlader samtalen nu.
Er trods alt på arbejde...

**Comment by ronan-mch** [comment]
lukker indtil @tadoh får sig en større enhed.
