### ISSUE TITLE
Klargørelse af forside til modkraft reklame

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#300]
På fredag får vi en banner reklame på Modkraft. Det kommer til at være plakaten med tilføjet info om at der er releasefest. Jeg tænker a banneret skal linke til forsiden. på den måde ser folk også resten af kalenderen. 

Jeg foreslår: 

1) At betatesteventet blir fjernet. Enten ved at du på en eller anden smart måde gør der usynligt eller jeg ændrer start tidspunktet til om lang tid, så det forsvinder fra "Kommende begivenheder". Vi linker så til betatesten med en  ny nyhed med navnet: "Duk Op er under konstruktion - giv feedback her"

2) Jeg fremhæver Releasefesten, så den kommer op i "kommende begivenheder".

Hvad tænker i andre?

**Comment by ronan-mch** [comment]
Hej,

Det lyder godt, du kan også ændre slut tidspunktet til et tidspunkt i
fortiden.

Ronan

2016-01-20 20:32 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Cool. Det prøver jeg.

**Comment by Siggik** [comment]
jeg kunne ikke sætte slut tidspunktet bagud i tid. Men jeg satte det til kl 21 i dag, inden den blev 21. Jeg synes selv jeg er smart:) Men den forbliver på forsiden. Forsvinder den først efter et fast interval eller er det en bug?

**Comment by ronan-mch** [comment]
huh, der er noget med at timezone på denne server er sat på amerikansk tid (it's on my list...) så det kunne godt være derfor at den ikke lige kan se at den er overstået.

**Comment by ronan-mch** [comment]
Den er væk nu. Fremhæv du bare releasefesten, så er alt godt.

**Comment by Siggik** [comment]
Det har jeg gjort. Men den kommer ikke op?

**Comment by Siggik** [comment]
Asylum vacation og sammen mod pegida er også promoverede. Men ikke koncerten oh spiseklubben. Burde den ikke overrule dem?

**Comment by Siggik** [comment]
Promoverings featuren driller mig. Mit mål: Jeg vil gerne have Releasefesten til at komme i "Den kommende tid" og jeg vil gerne have vegaterspiseklubben event til ikke at være der.

Det kan ikke lade sig gøre. Jeg tror reglen om at der skal være kronologi overruler mine forsøg. (Som er en cool regl)

En mulighed kunne evt. være at lave en feature der kunne de-promovere et event? Men har du mulighed for at lave en midlertidig løsning, så det ser nogenlunde ud i morgen?

**Comment by ronan-mch** [comment]
Ja, du har ret i din analyse (se koden her
https://github.com/ronan-mch/det_sker/blob/master/app/models/calendar.rb#L10
).

Jeg tror faktisk du vil kunne få den til at due vel at sørge for at mindst
5 events i fremtiden er highlighted. Derved vil den slet ikke kigge i de
almindelige events.

Jeg kan godt se at det er en bug i algoritmen men jeg har desværre ikke
mulighed for at lave en midlertidlig løsning da jeg tager på ferie fra i
morgen formiddag indtil søndag. I næste uge vil jeg kunne lave noget, men
der er det vist for sent.


2016-01-21 9:56 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
ok, jeg forstår ikke helt koden:) 

Jeg har nu 7 highlighted. Det ændrer hvis ikke noget.

**Comment by ronan-mch** [comment]
ok, jeg fatter det ikke sorry.
