### ISSUE TITLE
Fix link in creation alert

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#301]
kommentar fra  Annelise Witek på betattest eventet: https://dukop.dk/events/6?locale=da

**Comment by ronan-mch** [comment]
nå ja, det er sikkert noget der røg med forsiden. Før i tiden var det sådan at når man oprettet en event så fik man en lille link til hvor den stod på forsiden, dvs. at man scrollede ned på side til hvor eventen lå hen. Nu tænker jeg om det vil give mere mening at man bare linker til selve event siden i stedet for. Hvad synes I?
![green_link](https://cloud.githubusercontent.com/assets/1145457/12461041/26b8e992-bfb7-11e5-9367-f8bb8da6b820.png)

**Comment by ronan-mch** [comment]
eller måske skal man bare komme til event siden i stedet for forsiden?

**Comment by Siggik** [comment]
Vi(Tado og jeg ved køkkenbordet), synes at den grønne linje er fin. Så vi stemmer for et link i den grønne linje til eventet. Men man kommer til forsiden når man har oprettet eventet. Men det er ikke vigtigt for os.

**Comment by ronan-mch** [comment]
ok, det gøre jeg så. det er heller ikke hjerteblod for mig ;)
