### ISSUE TITLE
krav til QA

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#304]
Hej, @Siggik og @tadoh. Jeg går og retter nogle ting og vil lige høre jeres meninger mens I er ved køkkenbordet sammen. En af de ting jeg er meget utilfreds med ift. applikationen er at min test dækning ikke er særlig omfattende. Dvs, at ikke alle mulige scenarier bliver testet automatisk inden jeg lægger en ny udgave ud. Jeg forsøger at teste ting manuelt, men det er altid ting jeg ikke lige lægger mærk til. 

Derfor vil jeg høre jeg om jeres tanker ift. QA. Kunne I tænke jer at en ny udgave altid bliver lagt på en test site inden den kommer på produktion så I får lov til at lave manuel QA? Problemet er at det kræver lidt tid og kan derfor forsinke release processen. Det stiller også krav til jeres tid. En anden mulighed er at jeg investere tid i opdatering af min automatisk tests. Det kunne jeg rigtig godt tænke mig, men det betyder at mine tid går på det i stedet for rettelser og nye features som er heller ikke optimal.

Nogle tanker?

**Comment by Siggik** [comment]
Hej Ronan

Gode overvejelser. Vi tænker umiddelbart at det bedst at vi tester, så du har mest mulig tid til din kerne kompetence. 

Men hvordan vi præcis gør er godt spørgsmål. Vi foreslår at vi tager dette med i overvejelserne, når vi efter festen generelt, skal tænke over hvordan vi flodeler arejdsopgaver og organiserer i fremtiden. Daglige admins opgaver på siden, Løbende opreklamering/facebook administrering, viderudvikling af  siden. Herunder QA. og sikkert noget flere ting.

**Comment by ronan-mch** [comment]
ok, det synes jeg lyder fornuftigt. hvis vi laver en tjeklist over de ting der skal testes bliver det måske lidt mere overskuelig og så kan jeg også arbejde hen imod bedre automatisering når der er tid til det.

**Comment by ronan-mch** [comment]
Og nu vi snakker om det, jeg har lagt en opdateret udgave med dagens ændringer på den nye server så I kan se dem nu.

**Comment by ronan-mch** [comment]
Actually, det kan i måske vente med. Jeg laver nogle flere ting og laver en ny release i næste uge.

**Comment by Siggik** [comment]
Tjek
