### ISSUE TITLE
Et event er væk: MOnday café on Common ground...

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#307]
Fremgår kun under Bolsjefabrikken og ikke under de fasteaktivitere: https://dukop.dk/users/69?locale=da

**Comment by ronan-mch** [comment]
weird. aner ikke hvad der foregår.

2016-01-21 10:19 GMT+01:00 Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
Jeg har et gæt. Det er fordi at der først er sat til gentage fra mandag i næste uge? 

Hvis det er tilfældet, så vil det nok være smartere at den kom frem. F.eks.  dage før?

**Comment by ronan-mch** [comment]
nå ok, det giver mening. jeg kigger på det igen på et senere tidspunkt.
