### ISSUE TITLE
http cache control on static assets

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#310]
from jon.

Det kan dog godt blive meget hurtigere. På en mobil forbindelse er den største ventetid første opslag. Så selvom at der er ETags, så skal browseren stadig forbinde for at finde ud af om der er en ny version. Siden i bruger en hash på både CSS og JS, så er der ingen grund til at bruge ETags. I kan cache alt med hashes (det vil sige alt der ikke er selve html siden) i et års tid. Når i ligger en ny version op af jeres asset (.js,.css eller et billede), så skifter hash'en og browseren vil ikke bruge den cachet version.

Sæt følgende på alle assets (IKKE PÅ HTML):

Cache-Control:public, max-age=31536000 -> Sørger for at assets kan blive cachet på en proxy server (forkorter vejen fra A -> B)

Expires: Sun, 29 Jan 2017 12:24:12 GMT -> Sørger for at browseren loader fra cache og ikke først spørger serveren for ny indhold

Læs mere her: https://devcenter.heroku.com/articles/increasing-application-performance-with-http-cache-headers#http-cache-headers

Hvis i implementere det kan i skære et halvt sekund af load tiden (0,577 sekunder) i mit tilfælde.
Det man kan være sikker på ved en mobil forbindelse er at forbindelsen forsvinder helt. Selvom data forbindelsen er høj, lad os sige 2m/bit, så har du kun et vindue på måske et sekund og siden TCP starter langsomt, får du næsten aldrig fuld hastighed på et mobil netværk. https://en.wikipedia.org/wiki/Slow-start
Det betyder at hvis jeg mister forbindelsen og browseren skal lave en If-Modified request, så kan det tage 2-5-10 sekunder før jeg får en 304 og kan se siden.

https://devcenter.heroku.com/articles/http-caching-ruby-rails

**Comment by benjaoming** [comment]
Der er følgende problemer:

1) Header logo er ikke skaleret ned: 408 KB
2) CSS: 354 kB
3) JS: 558 KB


Normalt fylder Bootstrap ikke mere end ~100KB. Vores header kan også komme ned på 50 KB.

Så vi kan godt skære > 1MB data væk for første load.

**Comment by dotnetCarpenter** [comment]
Hvis i bruger Memcached :
    [Using Rack::Cache with Memcached to provide an HTTP cache store](https://devcenter.heroku.com/articles/rack-cache-memcached-rails31)

**Comment by tadoh** [comment]
@benjaoming er skalering af logoet noget, I/du kan gøre, eller skal jeg spørge Kristine som har lavet den sidste udgave af det? Og i det tilfælde, hvad er der brug for?

**Comment by benjaoming** [comment]
@tadoh kan vi sagtens, men jeg ved ikke lige hvordan logoet indsættes i koden p.t... der ligger et cache-lag henover, jeg ikke er med på :)

@ronan-cph

Eks:

    convert -resize 400x logo.png logo_small.png

**Comment by dotnetCarpenter** [comment]
@benjaoming @tadoh måske bliver det flottere hvis Kristine laver komprimeringen i photoshop eller lignende. Designere plejer at være pænt stramme over aggressive automatiserede komprimeringer. Bare min erfaring - jeg er total detalje blind og kan ikke selv se forskellen.

**Comment by ronan-mch** [comment]
nogle [interessant nginx moduler her](http://ngxpagespeed.com/) man kan bruge til at lave alle mulige optimerings tricks.

**Comment by dotnetCarpenter** [comment]
Husk at [srcset](http://responsiveimages.org) efterhånden har ret god understøttelse. Med `srcset` kan man angive forskellige billedestørrelser. Browseren vil så automagisk vælge den bedste størrelse i forhold til brugerens skærm. Så i kan lave en resize på jeres billeder og sætte det på jeres `<img srcset="` tags.

**Comment by benjaoming** [comment]
Fede tips, tak @dotnetCarpenter og @ronan-mch -- jeg skal se, om der er noget i nginx, der kan tweakes... men det er godt nok også en lang liste :)

**Comment by ronan-mch** [comment]
According to the [Rails asset guide](http://guides.rubyonrails.org/asset_pipeline.html#far-future-expires-header), we can add far future cache expiration through this snippet in nginx:
```
location ~ ^/assets/ {
  expires 1y;
  add_header Cache-Control public;
 
  add_header ETag "";
  break;
}
``

**Comment by tadoh** [comment]
@dotnetCarpenter @benjaoming jeg kan godt spørge Kris om at lave filen om. Hvad skal størrelsen være?

**Comment by ronan-mch** [comment]
Jeg har nu lagt ovenstående snippet i dukops nginx conf fil så der nu er far future cache expiry på:

```Expires:"Tue, 07 Feb 2017 20:16:16 GMT"```

Den regel gælder vist ikke for brugerenes billeder da de ligger i en anden mappe, burde den ikke også det?

Jeg har også opdaget at der var en fejl i den måde jeg kompileret assets på - hvis man ikke sætter `RAILS_ENV=production` foran kommandoen så bliver de kun concatenated og ikke minified. Jeg har lavet det igen og så er de blevet mindre:

```
css 354.68kb -> 137.56kb
js 558.99kb -> 253.17kb
```
Hvad skal det næste være?

**Comment by ronan-mch** [comment]
Ok nu også med en mindre udgave af logoet takket være @benjaoming s forslag. Den er reduceret fra 307k til 48k. Bemærk at det er ikke på produktion endnu, jeg vil gerne have QA på nogle andre ændringer inden jeg opdaterer app-en. Det kan dog ses på [Heroku](http://thawing-dawn-8343.herokuapp.com/) - jeg kan ærlig talt ikke se nogen forskel. Andre?

**Comment by ronan-mch** [comment]
Hvad siger I @benjaoming og @dotnetCarpenter  - er vi ved at være der?

**Comment by benjaoming** [comment]
Yeah man!! Det er bare super nice, synes ikke vi behøver tværer mere rundt
i optimering af det her, når nu aktuelt at første page load er ~½ MB.

**Comment by Siggik** [comment]
Det ser godt ud!

**Comment by ronan-mch** [comment]
Jeg er blevet lidt en speed freak af det her: nu vil jeg gerne prøve den der nginx plugin der laver billederne om til sprites. Men jeg venter indtil vi har en test server...

**Comment by dotnetCarpenter** [comment]
Det ser fint ud. I hvilke tilfælde vil du bruge sprites? Kan sikkert laves hurtigere i ren CSS....

**Comment by ronan-mch** [comment]
Det vil være til forsiden hvor der typisk vil være 4/5 bruger genereret billeder, derfor vil det ikke være realistisk at lave sprites manuelt.

**Comment by dotnetCarpenter** [comment]
Hmm.. Spites er gode til at minimere antal HTTP requests (som kun er vigtig for HTTP 1.1 og ikke SPDY protocol såsom HTTP 2.0 hvor antal HTTP requests er ligegyldig). MEN MEN MEN, brug aldrig sprites til billeder der er uafhængige af hinanden, fx brugerbilleder. En sprite er som regel et ret stort billede, nogen gange kæmpe. Hvis et billede i sprit'en skiftes skal alle billeder loades igen, dvs hele sprit'en skal downloades igen. Brugerbilleder fra forskellige aktører vil skifte uafhængig af hinanden og slutbrugeren vil skulle downloade alle billeder igen (hele sprit'en), så snart sprit'en skiftes. Sprites er også meget ufleksible. Fx kan du med `srcset` have et lille billede til mobil og et stort til desktop. Du kan skalere størrelsen af det viste billede i CSS, mellem de 2 størrelser. Men hvis du bruger et sprite, så betyder det noget hvordan billederne i sprit'en er placeret. Fx kan du ikke bare skalere en højde hvis billederne ligger vertikalt i sprit'en. Ellers kan du se det næste billede eller forrige billede, der hvor dit ene brugerbillede skal vises.

Det korte og det lange er, at sprites er en gammel, men nyttig måde at samle billeder på, men som regel altid den forkerte løsning til optimering.

Billede optimering bør være nogenlunde sådan her:

1. Brug de rigtige cache headers med querystring hash, så du helt undgår HTTP request. (appcache kan også bruges, men er svært at sætte rigtigt op - [hvis du ikke laver en SPA så undgå det](http://alistapart.com/article/application-cache-is-a-douchebag))
2. Optimere billede kvaliteten i forhold til udseende - gøres bedst af designere som er instrueret i at lave billeder som fylder lidt (i kb).
3. Lav flere forskellige størrelser af billedet, du kan bruge `srcset`, så det passer til den skærm billedet skal vises på.
4. Kig på komprimerings formater. Husk jpg/png/gif osv **er komprimerings formater**. Men til Chrome kan man fx lave WebP komprimering istedet for jpg/png.
5. Hvis billlede kun skifter sjældent eller aldrig, og **ikke** skal caches seperat, og **ikke** kan erstattes af en [font](https://fortawesome.github.io/Font-Awesome/), og **skal** preloades (fx image rollover eller animationer), så brug sprites.

Et eksempel på en god sprite: http://www.google.com/doodles/martha-grahams-117th-birthday
