### ISSUE TITLE
Translations for static texts

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#317]

**Comment by Siggik** [comment]
@tadoh lavede også nogle? Skal de nye tekster ikek genrelt med i den hye release også? Altså dem er er skrevet sikkerhedsteksten og de ny oversatte.

**Comment by ronan-mch** [comment]
Jo da, jeg var ret sikker på at de var med, men det er de vist ikke. Jeg
har dem nok liggende på en anden branch derhjemme.

2016-02-22 10:09 GMT+01:00 Siggik <notifications@github.com>:

**Comment by ronan-mch** [comment]
De er nu merget og lagt op på staging.
