### ISSUE TITLE
events ikke kronologisk under dage (se klokkeslettene)

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#321]
![screenshot from 2016-02-18 23 06 28](https://cloud.githubusercontent.com/assets/7570153/13159852/7731c3b4-d694-11e5-96b9-327f0fe1f4b4.png)

**Comment by ronan-mch** [comment]
Pinligt! Tak fordi du gøre mig opmærksom på det.

tor. 18. feb. 2016 23.08 skrev Siggik <notifications@github.com>:
