### ISSUE TITLE
Feedback på staging 28. februar

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#323]
Forskellige ting fundet på staging-serveren:

"om duk op"  teksen på engelsk er der ikke?

**Comment by Siggik** [comment]
Billederne ligger der ikke?

**Comment by Siggik** [comment]
jo, det gør de hvis med nye events.

**Comment by Siggik** [comment]
Det blev en lidt hurtig test med tømmmermænd. Men kunne ikke finde flere fejl. Jeg oprettede og rettede både i unikke og gentagenede events. Tado har hvis for mange tømmermænd til at teste i aften. Men han skriver selv.

**Comment by tadoh** [comment]
Hej

Akkurat som sigurd skriver - er for smadret for at kigge på det i aften. Beklager. 

Er allerede på vej i seng nu og kan prøve at lege med det i morgen hvis det stig giver mening? 

-------- Original message --------

**Comment by ronan-mch** [comment]
Ja,  jeg er også for smadret til at lave noget ;)

Den søn. 28. feb. 2016 20.35 skrev tadoh <notifications@github.com>:

**Comment by Siggik** [comment]
Filter bug: 
![screenshot from 2016-03-01 17 03 11](https://cloud.githubusercontent.com/assets/7570153/13432991/397ffc26-dfd0-11e5-9d99-06efc40da0b5.png)

**Comment by ronan-mch** [comment]
den får jeg slet ikke med FF på Ubuntu. Jon - har du nogen ide hvad der
sker?

**Comment by dotnetCarpenter** [comment]
@ronan-mch hmm ja. layout'et fungere ikke mellem 768px og 1000px.
@Siggik hvad er din skærmopløsning?

**Comment by Siggik** [comment]
1024x768 er min opløsning.
