### ISSUE TITLE
Admin dashboard

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#330]
Jeg har lavet en meget basic admin dashboard hvor man sortere i events efter oprettet tid eller opdateret tid. Den er på staging serveren nu. Jeg har gjort din konto der til admin hvis du vil kigge på det @Siggik...

**Comment by tadoh** [comment]
Feeeedt! 
Leger med det senere :)

-------- Original message --------

**Comment by ronan-mch** [comment]
ok, you don't have an admin account there so you'll probably have to use
Sigurd's. Or Sigurd can upgrade you to admin if you create an account...

2016-03-14 8:20 GMT+01:00 tadoh <notifications@github.com>:

**Comment by ronan-mch** [comment]
any comments?

**Comment by Siggik** [comment]
Tjekker det ud nu og gør tado til admin.

**Comment by Siggik** [comment]
Jeg synes det er ser smukt ud. Men på staging kan jeg som admin ikke se en liste over brugere? Så kan ikke gøre @tadoh  til admin, da der ikke ligger events på staging som han er har oprettet.

**Comment by Siggik** [comment]
How nu fandt jeg oversigten over brugere. Gir mening med den nye placering. Men kan stadig ikke gøre @tadoh til admin. Han har slet ikke en bruger på staging?

**Comment by ronan-mch** [comment]
Nej, vist ikke.

Den ons. 16. mar. 2016 17.16 skrev Siggik <notifications@github.com>:

**Comment by tadoh** [comment]
Det er mærkeligt. Jeg har oprettet den flere gange. Laver en ny nu.


-------- Original message --------

**Comment by ronan-mch** [comment]
Ja undskyld, det er nok fordi databasen der er blevet wipet et par gange.

**Comment by tadoh** [comment]
Har du wipet MIG?? :)
Har lavet en ny bruger nu, hvis du eller @siggik kan give mig admin rettigheder 

-------- Original message --------

**Comment by ronan-mch** [comment]
nu er du admin. remember, with great power comes great responsibility.

2016-03-17 10:35 GMT+01:00 tadoh <notifications@github.com>:

> Har du wipet MIG?? :)
> Har lavet en ny bruger nu, hvis du eller @siggik kan give mig admin
> rettigheder
>
> -------- Original message --------
> From: Ronan McHugh <notifications@github.com>
> Date:17/03/2016 09:56 (GMT+01:00)
> To: ronan-mch/det_sker <det_sker@noreply.github.com>
> Cc: tadoh <tado@riseup.net>
> Subject: Re: [det_sker] Admin dashboard (#330)
>
> Ja undskyld, det er nok fordi databasen der er blevet wipet et par gange.
>

**Comment by tadoh** [comment]
I like it! Meget simpelt og det gør det, det skal gøre. :+1:

**Comment by ronan-mch** [comment]
Godt at høre - er der nogle oplysninger I mangler på siden?

**Comment by Siggik** [comment]
Det tror jeg ikke. Men lidt svært at gennemskue på staging. Måske skal vi bare teste det fra nu af i funktion?

**Comment by ronan-mch** [comment]
Sorry sigge, jeg forstår ikke helt hvad du mener

Den lør. 19. mar. 2016 13.02 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
OK:) jeg mente bare admin dashboardet er klar til at blive implementeret på siden.

**Comment by ronan-mch** [comment]
Godt så.

**Comment by Siggik** [comment]
Dashboardet er optur. Det gør ret mange ting nemmere. 

2 forslag til at gøre det ekstra lækkert:

- Datoen  for eventet fremgår
- Serier blir kun vist som en eller de blir gemt væk under en fane eller lignende.

**Comment by ronan-mch** [comment]
Ok, jeg vil også gerne vise de serier der er udløbet på en særlig side.

Den tir. 19. apr. 2016 11.07 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
go idé!
