### ISSUE TITLE
Published flag on events

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#331]
True by default. If false, do not show on front page, but allow direct linking. This will enable admins to hide things they're not sure about.

**Comment by ronan-mch** [comment]
@Siggik og @tadoh, dette feature er nu lavet og oppe på staging. Feedback modtages gerne.

**Comment by tadoh** [comment]
Fedt! 
Er i Palæstina - kan først kigge på det om lidt over en uge. :)


-------- Original message --------

**Comment by Siggik** [comment]
Cool. Jeg har testet det:

Med faste events, ser der ud til at virke fint. Men med gentagende events forssvinder de ikke fra "faste begivenheder" forsiden.(Se Brunch i Folkets hus. ) 

Den forsvinder dog fra bruger-oversigten. Dvs. den man kan se når man ikke er logget ind som brugeren der har oprettet eventet.

**Comment by ronan-mch** [comment]
Hej,

Tak for feedback - jeg skjuler dem også fra de faste. Jeg forstår ikke helt
hvad du mener mht. bruger-oversigten. Jeg har programmeret det sådan at kun
vedkommende bruger kan se dem på sin egen bruger side men at alle brugere
kan se den hvis de får et link til den. Er det ikke det du ser?

Hilsner,

Ronan

**Comment by Siggik** [comment]
jo, præcis. Den er ikke her: http://staging.dukop.dk/users/34?locale=da . præcis som det skal være:)

**Comment by ronan-mch** [comment]
@Siggik - det burde være rettet nu...

**Comment by Siggik** [comment]
ja, det gør det!
