### ISSUE TITLE
Weekly events sidebar should include events starting within the next week

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#333]
Hvorfor fremtræder denne eventserie ikke af forsiden: https://dukop.dk/event_series/46  ?

**Comment by ronan-mch** [comment]
Hej Sigge,

Logikken i faste sidebar-en går ud på at vise alle de serier som er aktiv, som allerede er startet og er ugentligt. Som jeg husker det havde du lavede serien til at starte dagen efter og så oprettet sagen da den ikke var kommet på endnu. Det kunne godt være at det var en idé at ændre det til aktiv og starter indenfor de næste syv dage. Jeg tror at det vil løse problemet.

**Comment by Siggik** [comment]
gir go mening!
