### ISSUE TITLE
Sorry, blir ved med at glemme hvor jeg retter i teksterne på siden.

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#334]
Er det her: https://github.com/ronan-mch/det_sker/tree/master/config/locales

**Comment by ronan-mch** [comment]
ja, de fleste ting ligger i enten `da.yml` eller `en.yml`, bortset fra de lange about tekster som ligger i `about.en.yml` og `about.da.yml`. Vær sød at kør indholdet af den ændrede side gennem [YAMLLint](http://www.yamllint.com/) inden du gemmer.

**Comment by Siggik** [comment]
Dvs, at jeg skal afkrydse: "Create a new branch for this commit and start a pull reques"

**Comment by ronan-mch** [comment]
ja, lave en Pull Request tak.
