### ISSUE TITLE
Event picture size in highlights

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#335]
@Siggik siger:

> Jeg mindes at det et sted var snak om at gøre thumbnailene på forsiden større. Det er hvis ikke her, men i hvert fald. Det kunne være nice hvis de blev lidt større, så de mere passede med størrelsen på event-teksten:)

**Comment by ronan-mch** [comment]
nu lavet og oppe på staging.

**Comment by Siggik** [comment]
Cool. jeg har nu lagt billeder og tekst til eventsene på staging. For at teste det.

 Der et eller andet lidt skørt ved det nu. Er de lidt for store? Eller er det at de har forskellige former? Eller hvad er det. Eller er det måske ok?

**Comment by ronan-mch** [comment]
der er vist noget fucked med staging miljøet, jeg kunne ikke se nogle af dine billeder. Men jeg har prøvet at give den lidt mere padding, håber at det hjælper...

**Comment by Siggik** [comment]
Jeg har lige lavet 2 screenshots. En hvor jeg har zoomet ud og en normal.
![billede rpa staging forside](https://cloud.githubusercontent.com/assets/7570153/14155088/77e1aa58-f6c0-11e5-9ac8-3e0be4d7ff00.png)
![billede rpa staging forside2](https://cloud.githubusercontent.com/assets/7570153/14155095/7d5a07fa-f6c0-11e5-9c81-c5b167d1b83c.png)

**Comment by ronan-mch** [comment]
det har vist noget at gøre med aspect ratio af billedet. hvis det er
portrait så bliver den vist ok, hvis den er landscape så er der noget tom
rum under. Jeg tror ikke at der er meget jeg kan gøre for det. men jon
eller lars ved det sikkert
bedre end jeg gøre...

**Comment by Siggik** [comment]
@larsgaardsoe? Hvordan tagger man jon?

**Comment by ronan-mch** [comment]
@dotnetcarpenter
