### ISSUE TITLE
Current promoted events occur twice in highlights

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#336]
Se folkekøkken på makværket: https://dukop.dk/

**Comment by ronan-mch** [comment]
ok, det er fordi den er promoveret og ville også komme i highlights pga. tiden. Det er helt klart en bug i highlights koden, indtil videre har jeg rettet ved at fjern promoveringen men koden skal selvfølgelig også fixes.

**Comment by Siggik** [comment]
Tjek
