### ISSUE TITLE
gentagelses mulighed forlænget til 6 månedet

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#340]
Det er lige nu et ret stort arbejde at sørge for at folk hele tiden går ind og gentager dem. Det er et større problem at vi mangler begivenheder end at aflyste events er med i kaleneren. 

Kunne være fedt at få den med i den nye release og så kan advarselsfunktionen komme med i fremtiden.

**Comment by ronan-mch** [comment]
ok, det gøre jeg i aften.

**Comment by ronan-mch** [comment]
Nu oppe og testet på [Staging](http://thawing-dawn-8343.herokuapp.com/event_series/35?locale=da). Ser ud til at virke fint.

**Comment by Siggik** [comment]
Ja!
