### ISSUE TITLE
Calendar type view on User show page

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#342]
se siden

**Comment by ronan-mch** [comment]
er der faste begivenheder på disse dage? reglen hedder nu, indenfor den
næste uge, så dagens begivenheder er overstået, der er nok ikke noget i
morgen eller på lørdag så er der mandag, tirsdag og onsdag tilbage.

**Comment by Siggik** [comment]
ahh, det har du nok ret i. Kunne måske være godt at vise næste torsdags begivenheder? Gik lige ind for at tjekke på sportsrummet side. Den er helt skørt. Events fra februar ligger øverst og ingen ugedagenavne: 
![screenshot from 2016-04-14 23 25 02](https://cloud.githubusercontent.com/assets/7570153/14544244/7d205ed6-0298-11e6-8b88-35687e741bfc.png)

Alt andet er by the way nice! :)

**Comment by ronan-mch** [comment]
ok, det er lidt fjollet og nok hurtigt at fikse. Jeg er ud i byen i morgen
men jeg prøver at ordne det i weekenden.

**Comment by ronan-mch** [comment]
Two months late! Men den [burde være der nu](https://www.dukop.dk/users/69?locale=da). Ved ikke helt hvad der skete der...

**Comment by Siggik** [comment]
Ser perfekt ud!
