### ISSUE TITLE
tid og sted vises ikke prewiew når man laver opslag på facebook sider. Billedet heller ikke. Billedet virker dog i

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#343]
Billedet virker dog i grupper.

![dukop](https://cloud.githubusercontent.com/assets/7570153/14581139/99c6bace-03e4-11e6-9149-44c077d4dde5.png)

**Comment by ronan-mch** [comment]
Hej, så vidt som jeg kan se på FB gruppen så kommer tid og sted ind i titel linjen lige som forventet. Det rigtige billede bliver også vist og ikke logo-et. Hvis du ikke kan se det hele så er det fordi titlen er for lang. Det kan jeg ikke gøre noget ved. 

Billedet kommer ikke med i preview da Facebooks crawler skal vide hvor stor den er inden den kan sætte den ind. Det gøre den først efter du har lavet opslaget. Det er dog muligt at give den billede dimensionerne ind i metadata men jeg har valgt ikke at gøre det grundet nogle tekniske årsager (enten skal jeg gemme dem efter processering som vil kræve noget arbejde fra min side eller skal jeg kigge på filen hver gang siden bliver vist som vil øge page load tid). Det er muligt men jeg vil ikke prioritere det nu.

**Comment by Siggik** [comment]
ok, gir mening.

**Comment by Siggik** [comment]
Kan man gøre det således at det loget der kommer frem når man deler forsiden? Og at teksten er et eller andet relevant om DukOp og ikke noget om en en begivenhed?

**Comment by ronan-mch** [comment]
Ja, det kan man nok godt.

Den tir. 19. apr. 2016 11.04 skrev Siggik <notifications@github.com>:
