### ISSUE TITLE
Replace text based captcha with image based captcha

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#344]
The text based captcha can be defeated through use of a simple script. Image based captchas are breakable as well, but should be more robust than the text based check currently in use.

**Comment by ronan-mch** [comment]
looks like this doesn't work on all on staging. My assumption is that it's because imagemagick isn't installed there, but I'm not sure...

**Comment by ronan-mch** [comment]
@Siggik og @tadoh - det er nu implementeret og aktiv på sitet. Det er ikke så optimalt at I ikke havde tid til at teste det første men det skyldes at det brændte lidt på med at få server migreret da vores tidligere hosting firma var gået konkurs. Anyway, hvis I har nogle feedback skal I være velkommen til at komme med det nu.

**Comment by Siggik** [comment]
Helt sikkert. Jeg må dog indrømme jeg ikke helt fatter hvad capthca er? :)

**Comment by dotnetCarpenter** [comment]
@ronan-mch har du prøvet en honning pot løsning som captcha? I teorien lyder det jo meget bedre end at belemre brugere med bot bekæmpelse. Men jeg har ingen praktisk erfaring med det.

**Comment by ronan-mch** [comment]
Jeg har prøvet det før men der var stadig nogle der kom igennem.

Den ons. 11. maj 2016 14.25 skrev Jon Ege Ronnenberg <
notifications@github.com>:

**Comment by Siggik** [comment]
![screenshot from 2016-05-11 20 14 08](https://cloud.githubusercontent.com/assets/7570153/15191454/0d6966d2-17b5-11e6-9c86-c16fe00b765a.png)

Uden at slette min cache, fik jeg stadig ovenstående fejl. Kan man gøre noget for at det ikke sker for andre? Men efter slettede cache, så virker den igen.

**Comment by ronan-mch** [comment]
Jeg laver lige denne fejl side om så den indeholder en reference til en
ClearYourCache vejledning...

**Comment by dotnetCarpenter** [comment]
@ronan-mch måske kan du bare lave en force opdatering.
```html
<script>location.reload(true)</script>
```
>http://devdocs.io/dom/location/reload

**Comment by ronan-mch** [comment]
Tak, jeg prøver det.

**Comment by ronan-mch** [comment]
ok, hvad fanden foregår der her? når jeg prøver at gå til dukop.dk i en
privat vindue eller i Chrome så bliver jeg omdirigeret til new.dukop.dk! Er
der en eller anden DNS server derude der har fået noget galt i halsen? Jeg
kan ikke finde nogen reference til new.dukop.dk i server config den en
eller det andet sted, så kan det være andet end en DNS miskonfiguration?

**Comment by ronan-mch** [comment]
ok, der var en linje i `sites-enabled/default` hvor der stod `location new.dukop.dk dukop.dk`. Det har jeg nu fjernet. De tests jeg har prøvet ser ud til at virke, @benjaoming - kan du bekræfte?

**Comment by ronan-mch** [comment]
#349
