### ISSUE TITLE
Siden er stadig nede? Jeg skal gå igennem private window og acceptere et sikkerheds huld for at få adgang. 

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#349]
@benjaoming

**Comment by dotnetCarpenter** [comment]
Lyder som et certifikat problem. Har i ikke lige flyttet server? Jeg kommer fint ind på https://www.dukop.dk/ fra Sverige. Prøv at slette din browser cache. Se https://kb.iu.edu/d/ahic eller http://www.refreshyourcache.com/en/home/

**Comment by ronan-mch** [comment]
ja ny server og så er det efter ønske ikke dukop.dk længere men www.dukop.dk.

**Comment by Siggik** [comment]
www.dukop.dk gir mig stadig: 
"Duk Op is down

We are moving Duk Op to a faster server in order to improve application performance. Unfortunately this means some downtime this evening.

We'll be back up again before too long."

Og untrusted via private window.

At slette cache vil nok rette det første, men det retter det jo ikke for alle andre?

**Comment by benjaoming** [comment]
Jeg har lagt Jons link ind på den gamle servers fejlside.

Jeg regenererer certifikater på den nye server nu.

**Comment by tadoh** [comment]
Jeg blev også omdirigeret på New.dukop.dk i går og så på magisk vis videre efter nogle forsøg.Det virker fint for mig nu..

-------- Original message --------

**Comment by benjaoming** [comment]
Har genereret nyt certifikat og aktiveret det. Kan bekræfte, at det virker her. Jeg undrer mig lidt over, hvordan der kunne opstå problemer med det, der blev kopieret fra den gamle server.

**Comment by dotnetCarpenter** [comment]
Mon ikke det er noget stale DNS hos en ISP eller 2? Hvad er jeres [TTL](www.google.com/search?q=dns+ttl)?

**Comment by benjaoming** [comment]
TTL er automatic / 30 min.

Jeg tror måske, at problemet var, at www.dukop.dk var et CNAME, der pegede på "dukop.dk" -- det kan være, at dukop.dk har haft en ændret A record, men at CNAME for "www.dukop.dk" på en eller anden måde caches enten i browsere eller hos ISPer?
