### ISSUE TITLE
Et event 2 visninger på forsiden

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#353]
Det er dette event: https://www.dukop.dk/events/638?locale=da

Hvis man skjuler eventet, så forsvinder begge visninger. Så det er hvis et event?

**Comment by ronan-mch** [comment]
Nej, en er 638 den anden er 639. Jeg ved dog ikke hvorfor der er to af de
samme, mon ikke det er en bruger fejl?

Den lør. 14. maj 2016 15.57 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
ok, det er underligt. Nu har jeg "un" publiceret én serie. De er begge ikke synelige på forsiden?

**Comment by ronan-mch** [comment]
Det er 2 events i det samme serie. Kan du ikke unpublicere en enkelt event
frem for hele serien?

Den lør. 14. maj 2016 16.30 skrev Siggik <notifications@github.com>:

**Comment by Siggik** [comment]
jo, det virker.
