### ISSUE TITLE
Jeg kan ikke komme forbi bot-tjekkeren

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#354]
Kan I https://www.dukop.dk/anonymous_user?locale=da ? je gprøvede 8 forskellige..

**Comment by ronan-mch** [comment]
ja det har du ret i. Jeg kan ikke helt gennemskue hvorfor den ikke virker.
Jeg laver en post om det med det samme og prøver at finde en løsning...

**Comment by ronan-mch** [comment]
jeg har lavet en fix - og opdaterer med det samme. Jeg beklager fejlen.

**Comment by Siggik** [comment]
Cool. Det virker nu. Jeg fjerner nyheden?

**Comment by ronan-mch** [comment]
Ja

Den man. 16. maj 2016 15.50 skrev Siggik <notifications@github.com>:
