### ISSUE TITLE
kan ikke komme ind på dukop.dk eller www.dukop.dk via browser vindue på firefox og chrome

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#358]

**Comment by ronan-mch** [comment]
hvad mener du? Du skriver et minut senere som om du har set analytics
feature, så jeg går ud fra at du er kommet igennem...

**Comment by Siggik** [comment]
Ja, men kun gennem en Google søgning.

**Comment by Siggik** [comment]
På Firefox på mobil, kan jeg ikke skrive dukop.dk, men www.dukop.dk virker.

**Comment by Siggik** [comment]
Ok, jeg støder ind i det her problem ret tidt. I min egen browser på debian med iceweasel er det ikke et problem. Men det er det i privatevindue. Måske at der gemt noget i cache eller lignende som løser problemet. Men på andres computere så virker urlen kun hvis det er den lange: https://www.dukop.dk

**Comment by dotnetCarpenter** [comment]
DNS virker til at være forkert sat op.

```
$ host -t a www.dukop.dk
$ www.dukop.dk has address 82.196.11.111
$ host -t a dukop.dk
$ dukop.dk has address 82.196.11.111
```

https://www.networking4all.com/en/support/domain+names/dns/cname-records/

```
$ host -t cname dukop.dk
dukop.dk has no CNAME record
$ host -t cname www.dukop.dk
www.dukop.dk has no CNAME record
```

`www.dukop.dk` og `dukop.dk` peger på den samme IP. Det er forkert. `dukop.dk` skal pege på `www.dukop.dk` som peger på en IP. Normalt bruger man CNAME, men CNAME er **ikke** sat op.

**Comment by dotnetCarpenter** [comment]
Hvis i har noget server redirect (30*), så fjern det. En server redirect bruger ikke Internettet arkitektur (proxy servers, DNS tables etc), men kommunikere direkte med browseren (med mindre caching er sat, men nu bliver det hele meget mere kompliceret end det behøver). Det er som regel ikke det du gerne vil.
RFC 2616 er din ven :) https://www.ietf.org/rfc/rfc2616.txt

**Comment by benjaoming** [comment]
@dotnetCarpenter tak for forklaringen, det er også rigtigt, at vi har haft et CNAME og kom til at fjerne det ved migration og derefter er det en HTTP redirect, der har stået for at pege videre på www.dukop.dk

Ret nice at få CNAME op, det burde være i effekt efter næste TTL... 30 min...

**Comment by benjaoming** [comment]
@dotnetCarpenter har eksperimenteret både med CNAME og URL redirect på DNS niveau. Men det hjalp ikke umiddelbart.

fejlen var i HTTP serveren, f.eks.:

```
➜  ~ wget http://82.196.11.111
--2016-07-04 22:56:14--  http://82.196.11.111/
Connecting to 82.196.11.111:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https:/// [following]
https:///: Invalid host name.
```

Jeg kigger på det nu.

**Comment by benjaoming** [comment]
Det burde virke fint nu, der var brugt en forkert variabel `$server_name` i stedet for `$host` i vores Nginx redirect, så den sendte ovenstående forkert 301.

**Comment by benjaoming** [comment]
Jeg tør godt lukke den her nu, fordi der var en alvorligt dum fejl, men test gerne @Siggik 

Fejlen så ud til at dreje sig om `http://dukop.dk` mens `http://www.dukop.dk` virkede.

**Comment by Siggik** [comment]
Det virker for mig! Fedt!

**Comment by ronan-mch** [comment]
Tak for indsatsen @benjaoming !
