### ISSUE TITLE
RSS feed sends no pictures

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#360]
I sat down with Biveke from IF and we had a chat about the RSS feed.
There are three things we talked about and I am going to open separate issuses

RSS feed in IF's page appears with no pictures, also for the events with the picture. B admitted that she didn't know if it is the settings on the Duk Op end or the IF end, that cause it. Are we sure that our settings are sending pictures?

**Comment by ronan-mch** [comment]
det var på Duk Op siden. Det er nu tilføjet til RSS outputtet med `enclosure` elementet.

http://cyber.law.harvard.edu/rss/rss.html#ltenclosuregtSubelementOfLtitemgt

**Comment by ronan-mch** [comment]
Her er en eksempel: https://www.dukop.dk/users/69.rss?locale=da
