### ISSUE TITLE
usædvanlig meget aktivitet på i siden. Nogen der kan gennemskue hvorfor. 

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#363]
De andre dage med mere end gennemsnitlig aktivitet, er dage med et populært facebook opslag som er blevet set af mange. Men sådan et var der ikke i går. Kan nogen gennemsku hvorfor?

Den øgede aktivitet er både på events, forside, og location. 

se her selv: 

https://www.dukop.dk/admin/analytics/timeseries?utf8=%E2%9C%93&view=events%23show&interval=day&commit=Go

https://www.dukop.dk/admin/analytics/timeseries?utf8=%E2%9C%93&view=locations%23show&interval=day&commit=Go

https://www.dukop.dk/admin/analytics/timeseries?utf8=%E2%9C%93&view=calendar%23index&interval=day&commit=Go

**Comment by ronan-mch** [comment]
jeg tjekkede det er redirect problem en del gange ;)

**Comment by Siggik** [comment]
:)
