### ISSUE TITLE
igangværende event ikke synlig på brugerside

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#364]
Men er tilstede på forsiden. Det er fællestogturen til malmø. 

![screenshot from 2016-07-06 11 34 08](https://cloud.githubusercontent.com/assets/7570153/16613713/cf7ebaea-436d-11e6-960d-0a4b0c818a39.png)

**Comment by Siggik** [comment]
buggen er der igen: 
![screenshot from 2016-08-05 15 36 12](https://cloud.githubusercontent.com/assets/7570153/17438438/1f042bd2-5b23-11e6-957d-3b5072704708.png)

Dette event: https://www.dukop.dk/events/1244

**Comment by ronan-mch** [comment]
Tak, jeg kigger på det.

**Comment by ronan-mch** [comment]
Mystery solved! :balloon: Fejlen kan nemlig ses i den der debug output hvis man kigger efter `end_time`. Forsidealgoritmen tager de events hvor slut tid er efter nu. Men denne event starter i aften og sluttede i morges kl 03! Dvs at den ikke kan ses i dag da den allerede er færdig.  Det er tydeligvis tale om en bruger fejl i at de sat sluttiden forkert men jeg synes også at det er en UX fejl i at man må lave sådan en event. Jeg prøver at lave en fix i aften. Inden der vil jeg bare ændre på sluttiden så den kommer med igen...

**Comment by Siggik** [comment]
Cool, godt fundet!
