### ISSUE TITLE
Event er forsvundet fra forside og brugerside, men ikke stedside.

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#368]
Dette event er ikke synligt på forsiden eller bruger siden: https://www.dukop.dk/events/1219?locale=da

Men er stadig synligt på stedsiden. 

Jeg fandt eventet ved at at systemantisk indtaste forskellige nr i url'en. Men kunne f.eks. ikke se gamle events eller dettte events i dashboardet. 

Det kunne være sejt, hvis admin(og faktisk måske alle!) kunne se gamle events. Eller hvad tænker i andre? se: #367

**Comment by Siggik** [comment]
Hov, den er ikke synlig på stedsiden, det var et andet event.

**Comment by ronan-mch** [comment]
Hej Sigge, jeg kan desværre ikke se med det samme hvad problemet er. Det virker som vi har en luskede timings bug i applikationen. Det er svært at identificere fordi når jeg får tiden til det, kan jeg ikke se hvordan applikationen opfatter tid. For at hjælpe lidt med diagnosticering har jeg tilføjet en ny view til applikationen, se f.eks: https://www.dukop.dk/events/1228/debug?locale=da. Når du opdager sådan nogle problemer i fremtiden, må du meget gerne gå til denne visning og kopi klistre hele teksten til din issue.
