### ISSUE TITLE
Grafisk glitch på forsiden

### ISSUE THREAD

**Issue by tadoh** [ronan-mch/det_sker#371]
Jeg mener at det er sket før, men kan ikke finde den issue jeg lavede dengang...

Se her - det skifter når jeg scroller ned og den går tilbage på plads, når jeg scroller op igen. Det sker lige efter "Vis kun" overskriften forsvinder.

![screenshot from 2016-08-10 20-01-43](https://cloud.githubusercontent.com/assets/7386049/17565009/dc6aa078-5f35-11e6-8748-619a8bc539d7.png)
![screenshot from 2016-08-10 20-01-48](https://cloud.githubusercontent.com/assets/7386049/17565008/dc67dcbc-5f35-11e6-883c-98eb91c643f8.png)

**Comment by Siggik** [comment]
ja, det skete også på min gamle computer, på min nye sker det med det samme jeg begynder scolle bare en milliemeter.

**Comment by ronan-mch** [comment]
hi, I think I have fixed it now. Can you both please check it on your different screens to make sure it works for you?

**Comment by Siggik** [comment]
Det virker fint for mig! Nice!

**Comment by tadoh** [comment]
også her, cool!

**Comment by ronan-mch** [comment]
ok, jeg lukker.
