### ISSUE TITLE
Mulighed for at gentage events hver anden uge

### ISSUE THREAD

**Issue by ronan-mch** [ronan-mch/det_sker#376]
Mange event serier gentages i lige eller ulige uger. Det er der ikke mulighed for i den nuværende system hvor events kan gentages hver uge, eller den første, anden eller sidst i måneden. Derfor skal vi lave en ekstra mulighed der hedder **hver anden uge**. Det betyder at man skal ændre i metoden [EventSeries#create_events](https://github.com/ronan-mch/det_sker/blob/master/app/models/event_series.rb#L59) og tilføje en ekstra clause til `if` blocken. Du skal også lave en ekstra option i den [tilhørende dropdown](https://github.com/ronan-mch/det_sker/blob/master/app/views/event_series/_repeating_control.html.erb#L8-L12) plus locale strings. Den model del af koden bliver nok den mest tricky og jeg har heldigvis en [spec du kan bruge](https://github.com/ronan-mch/det_sker/blob/master/spec/models/event_series_spec.rb#L27-L35) til at hjælpe dig med debug. Skriv bare hvis der er noget du er i tvivl om noget.

**Comment by surpluscode** [comment]
PR: https://github.com/ronan-mch/det_sker/pull/378

Note that some tests fail.

**Comment by ronan-mch** [comment]
This is now in production. Apologies for the delay.

**Comment by Siggik** [comment]
Fedt!
