### ISSUE TITLE
Spring fra bund til top ved ned scrolling

### ISSUE THREAD

**Issue by Siggik** [ronan-mch/det_sker#377]
På den nuværende forside kan jeg ikke scrolle helt ned, uden at blive rykket op til begyndelsen af "Hele kalenderen", hvis jeg har valgt kun at se "Albertslund musikteater".

**Comment by ronan-mch** [comment]
hej @Siggik, jeg synes egentlig ikke at det kan betragtes som en bug. Man springer ikke til toppen som sådan i denne eksempel, sagen er at siden bliver så meget mindre (fordi der kun er en event synligt) at toppen og bunden er begge to i den samme vindue uden at man skal scrolle ned.

**Comment by Siggik** [comment]
hmm, så et design issue? :) Det sker hver gang man kun har et event.

**Comment by ronan-mch** [comment]
jeg forstår ikke helt hvorfor det er en bug - kan du ikke se eventet når du har klikket? Eller mener du at den ikke er synligt nok i forhold til det andet?

**Comment by Siggik** [comment]
Jeg mener det er en bug/designfejl, da jeg f.eks. ikke kan gå ned og se stederne i højre hjørne, da den springer op øverst hver gang jeg forsøger. Og det klart ikke opleves som det er med vilje at det sker på siden. Jeg skal faktisk vælge så mange events at det fylder hele min skærm, for at det ikke sker. Her sker det ikke: 
![screenshot at 2016-09-20 09-50-54](https://cloud.githubusercontent.com/assets/7570153/18661853/06835254-7f18-11e6-9bd7-9d2719d158e4.png)
